var track_baza_1 = 
{
    "staze": [
{
"id": 1,
"tip": "markirana",
"grupa": 1,
"ime": "PS_FG_CortanovackaTransverzala",
"gpxime": "PS_FG_CortanovackaTransverzala.gpx",
"oznaka": "CrvenoBela_Kruznica_Standardna_32.png",
"stil": "crvena_0",
"duzina": 1,
"tezina": 1,
"lepota": 1,
"uspon": 1,
"spust": 1,
"polazak": ["Popovica","Zmajevac"],
"mark": 1,
"bus": 1,
"bike": 1,
"kruzna": 1,
"opis1":"Jako lepa staza",
"opsirnije":"0",
"t_geojson":{},
"id_u_nizu": 99999
},
{
"id": 2,
"tip": "markirana",
"grupa": 1,
"ime": "PS_FG_EvropskiPesackiPut_E7",
"gpxime": "PS_FG_EvropskiPesackiPut_E7.gpx",
"oznaka": "CrvenoZuta_Kruznica_E7_32.png",
"stil": "crvena_0",
"duzina": 1,
"tezina": 1,
"lepota": 1,
"uspon": 1,
"spust": 1,
"polazak": ["Popovica","Zmajevac"],
"mark": 1,
"bus": 1,
"bike": 1,
"kruzna": 1,
"opis1":"Jako lepa staza",
"opsirnije":"0",
"t_geojson":{},
"id_u_nizu": 99999
},
{
"id": 3,
"tip": "markirana",
"grupa": 1,
"ime": "PS_FG_Transverzala",
"gpxime": "PS_FG_Transverzala.gpx",
"oznaka": "FGTransverzala_32.png",
"stil": "crvena_0",
"duzina": 1,
"tezina": 1,
"lepota": 1,
"uspon": 1,
"spust": 1,
"polazak": ["Popovica","Zmajevac"],
"mark": 1,
"bus": 1,
"bike": 1,
"kruzna": 1,
"opis1":"Jako lepa staza",
"opsirnije":"0",
"t_geojson":{},
"id_u_nizu": 99999
},
{
"id": 4,
"tip": "markirana",
"grupa": 1,
"ime": "PS_FG_TransverzalaSremskiFront",
"gpxime": "PS_FG_TransverzalaSremskiFront.gpx",
"oznaka": "CrvenoBela_Kruznica_Standardna_32.png",
"stil": "crvena_0",
"duzina": 1,
"tezina": 1,
"lepota": 1,
"uspon": 1,
"spust": 1,
"polazak": ["Popovica","Zmajevac"],
"mark": 1,
"bus": 1,
"bike": 1,
"kruzna": 1,
"opis1":"Jako lepa staza",
"opsirnije":"0",
"t_geojson":{},
"id_u_nizu": 99999
},
{
"id": 5,
"tip": "markirana",
"grupa": 1,
"ime": "PS_FG_VodopadskaTransverzala",
"gpxime": "PS_FG_VodopadskaTransverzala.gpx",
"oznaka": "Vodopadska_32.png",
"stil": "crvena_0",
"duzina": 1,
"tezina": 1,
"lepota": 1,
"uspon": 1,
"spust": 1,
"polazak": ["Popovica","Zmajevac"],
"mark": 1,
"bus": 1,
"bike": 1,
"kruzna": 1,
"opis1":"Jako lepa staza",
"opsirnije":"0",
"t_geojson":{},
"id_u_nizu": 99999
},
{
"id": 6,
"tip": "markirana",
"grupa": 1,
"ime": "PS_FG_Zanatlijska",
"gpxime": "PS_FG_Zanatlijska.gpx",
"oznaka": "CrvenoBela_Kruznica_Standardna_32.png",
"stil": "crvena_0",
"duzina": 1,
"tezina": 1,
"lepota": 1,
"uspon": 1,
"spust": 1,
"polazak": ["Popovica","Zmajevac"],
"mark": 1,
"bus": 1,
"bike": 1,
"kruzna": 1,
"opis1":"Jako lepa staza",
"opsirnije":"0",
"t_geojson":{},
"id_u_nizu": 99999
},
{
"id": 7,
"tip": "markirana",
"grupa": 2,
"ime": "PS_FGM_01_UltraEkstremni_UTMB4",
"gpxime": "PS_FGM_01_UltraEkstremni_UTMB4.gpx",
"oznaka": "FGMaraton_32.png",
"stil": "crvena_1",
"duzina": 1,
"tezina": 1,
"lepota": 1,
"uspon": 1,
"spust": 1,
"polazak": ["Popovica","Zmajevac"],
"mark": 1,
"bus": 1,
"bike": 1,
"kruzna": 1,
"opis1":"Jako lepa staza",
"opsirnije":"0",
"t_geojson":{},
"id_u_nizu": 99999
},
{
"id": 8,
"tip": "markirana",
"grupa": 2,
"ime": "PS_FGM_02_Ultra_UTMB3",
"gpxime": "PS_FGM_02_Ultra_UTMB3.gpx",
"oznaka": "FGMaraton_32.png",
"stil": "crvena_1",
"duzina": 1,
"tezina": 1,
"lepota": 1,
"uspon": 1,
"spust": 1,
"polazak": ["Popovica","Zmajevac"],
"mark": 1,
"bus": 1,
"bike": 1,
"kruzna": 1,
"opis1":"Jako lepa staza",
"opsirnije":"0",
"t_geojson":{},
"id_u_nizu": 99999
},
{
"id": 9,
"tip": "markirana",
"grupa": 2,
"ime": "PS_FGM_03_VelikiJuzni",
"gpxime": "PS_FGM_03_VelikiJuzni.gpx",
"oznaka": "FGMaraton_32.png",
"stil": "crvena_1",
"duzina": 1,
"tezina": 1,
"lepota": 1,
"uspon": 1,
"spust": 1,
"polazak": ["Popovica","Zmajevac"],
"mark": 1,
"bus": 1,
"bike": 1,
"kruzna": 1,
"opis1":"Jako lepa staza",
"opsirnije":"0",
"t_geojson":{},
"id_u_nizu": 99999
},
{
"id": 10,
"tip": "markirana",
"grupa": 2,
"ime": "PS_FGM_04_VelikiZapadni",
"gpxime": "PS_FGM_04_VelikiZapadni.gpx",
"oznaka": "FGMaraton_32.png",
"stil": "crvena_1",
"duzina": 1,
"tezina": 1,
"lepota": 1,
"uspon": 1,
"spust": 1,
"polazak": ["Popovica","Zmajevac"],
"mark": 1,
"bus": 1,
"bike": 1,
"kruzna": 1,
"opis1":"Jako lepa staza",
"opsirnije":"0",
"t_geojson":{},
"id_u_nizu": 99999
},
{
"id": 11,
"tip": "markirana",
"grupa": 2,
"ime": "PS_FGM_05_VelikiIstocni_UTMB2",
"gpxime": "PS_FGM_05_VelikiIstocni_UTMB2.gpx",
"oznaka": "FGMaraton_32.png",
"stil": "crvena_1",
"duzina": 1,
"tezina": 1,
"lepota": 1,
"uspon": 1,
"spust": 1,
"polazak": ["Popovica","Zmajevac"],
"mark": 1,
"bus": 1,
"bike": 1,
"kruzna": 1,
"opis1":"Jako lepa staza",
"opsirnije":"0",
"t_geojson":{},
"id_u_nizu": 99999
},
{
"id": 12,
"tip": "markirana",
"grupa": 2,
"ime": "PS_FGM_06_SrednjiIstocni_UTMB1",
"gpxime": "PS_FGM_06_SrednjiIstocni_UTMB1.gpx",
"oznaka": "FGMaraton_32.png",
"stil": "crvena_1",
"duzina": 1,
"tezina": 1,
"lepota": 1,
"uspon": 1,
"spust": 1,
"polazak": ["Popovica","Zmajevac"],
"mark": 1,
"bus": 1,
"bike": 1,
"kruzna": 1,
"opis1":"Jako lepa staza",
"opsirnije":"0",
"t_geojson":{},
"id_u_nizu": 99999
},
{
"id": 13,
"tip": "markirana",
"grupa": 2,
"ime": "PS_FGM_07_SrednjiZapadni",
"gpxime": "PS_FGM_07_SrednjiZapadni.gpx",
"oznaka": "FGMaraton_32.png",
"stil": "crvena_1",
"duzina": 1,
"tezina": 1,
"lepota": 1,
"uspon": 1,
"spust": 1,
"polazak": ["Popovica","Zmajevac"],
"mark": 1,
"bus": 1,
"bike": 1,
"kruzna": 1,
"opis1":"Jako lepa staza",
"opsirnije":"0",
"t_geojson":{},
"id_u_nizu": 99999
},
{
"id": 14,
"tip": "markirana",
"grupa": 2,
"ime": "PS_FGM_08_SrednjiJuzni",
"gpxime": "PS_FGM_08_SrednjiJuzni.gpx",
"oznaka": "FGMaraton_32.png",
"stil": "crvena_1",
"duzina": 1,
"tezina": 1,
"lepota": 1,
"uspon": 1,
"spust": 1,
"polazak": ["Popovica","Zmajevac"],
"mark": 1,
"bus": 1,
"bike": 1,
"kruzna": 1,
"opis1":"Jako lepa staza",
"opsirnije":"0",
"t_geojson":{},
"id_u_nizu": 99999
},
{
"id": 15,
"tip": "markirana",
"grupa": 2,
"ime": "PS_FGM_09_MaliIstocniEkstremni",
"gpxime": "PS_FGM_09_MaliIstocniEkstremni.gpx",
"oznaka": "FGMaraton_32.png",
"stil": "crvena_1",
"duzina": 1,
"tezina": 1,
"lepota": 1,
"uspon": 1,
"spust": 1,
"polazak": ["Popovica","Zmajevac"],
"mark": 1,
"bus": 1,
"bike": 1,
"kruzna": 1,
"opis1":"Jako lepa staza",
"opsirnije":"0",
"t_geojson":{},
"id_u_nizu": 99999
},
{
"id": 16,
"tip": "markirana",
"grupa": 2,
"ime": "PS_FGM_10_MaliZapadniEkstremni",
"gpxime": "PS_FGM_10_MaliZapadniEkstremni.gpx",
"oznaka": "FGMaraton_32.png",
"stil": "crvena_1",
"duzina": 1,
"tezina": 1,
"lepota": 1,
"uspon": 1,
"spust": 1,
"polazak": ["Popovica","Zmajevac"],
"mark": 1,
"bus": 1,
"bike": 1,
"kruzna": 1,
"opis1":"Jako lepa staza",
"opsirnije":"0",
"t_geojson":{},
"id_u_nizu": 99999
},
{
"id": 17,
"tip": "markirana",
"grupa": 2,
"ime": "PS_FGM_11_MaliZapadni",
"gpxime": "PS_FGM_11_MaliZapadni.gpx",
"oznaka": "FGMaraton_32.png",
"stil": "crvena_1",
"duzina": 1,
"tezina": 1,
"lepota": 1,
"uspon": 1,
"spust": 1,
"polazak": ["Popovica","Zmajevac"],
"mark": 1,
"bus": 1,
"bike": 1,
"kruzna": 1,
"opis1":"Jako lepa staza",
"opsirnije":"0",
"t_geojson":{},
"id_u_nizu": 99999
},
{
"id": 18,
"tip": "markirana",
"grupa": 2,
"ime": "PS_FGM_12_MaliIstocni",
"gpxime": "PS_FGM_12_MaliIstocni.gpx",
"oznaka": "FGMaraton_32.png",
"stil": "crvena_1",
"duzina": 1,
"tezina": 1,
"lepota": 1,
"uspon": 1,
"spust": 1,
"polazak": ["Popovica","Zmajevac"],
"mark": 1,
"bus": 1,
"bike": 1,
"kruzna": 1,
"opis1":"Jako lepa staza",
"opsirnije":"0",
"t_geojson":{},
"id_u_nizu": 99999
},
{
"id": 19,
"tip": "markirana",
"grupa": 2,
"ime": "PS_FGM_13_MaliZapadZapad",
"gpxime": "PS_FGM_13_MaliZapadZapad.gpx",
"oznaka": "FGMaraton_32.png",
"stil": "crvena_1",
"duzina": 1,
"tezina": 1,
"lepota": 1,
"uspon": 1,
"spust": 1,
"polazak": ["Popovica","Zmajevac"],
"mark": 1,
"bus": 1,
"bike": 1,
"kruzna": 1,
"opis1":"Jako lepa staza",
"opsirnije":"0",
"t_geojson":{},
"id_u_nizu": 99999
},
{
"id": 20,
"tip": "markirana",
"grupa": 2,
"ime": "PS_FGM_14_PripravnickiJuzni",
"gpxime": "PS_FGM_14_PripravnickiJuzni.gpx",
"oznaka": "FGMaraton_32.png",
"stil": "crvena_1",
"duzina": 1,
"tezina": 1,
"lepota": 1,
"uspon": 1,
"spust": 1,
"polazak": ["Popovica","Zmajevac"],
"mark": 1,
"bus": 1,
"bike": 1,
"kruzna": 1,
"opis1":"Jako lepa staza",
"opsirnije":"0",
"t_geojson":{},
"id_u_nizu": 99999
},
{
"id": 21,
"tip": "markirana",
"grupa": 2,
"ime": "PS_FGM_15_PripravnickiZapadZapad",
"gpxime": "PS_FGM_15_PripravnickiZapadZapad.gpx",
"oznaka": "FGMaraton_32.png",
"stil": "crvena_1",
"duzina": 1,
"tezina": 1,
"lepota": 1,
"uspon": 1,
"spust": 1,
"polazak": ["Popovica","Zmajevac"],
"mark": 1,
"bus": 1,
"bike": 1,
"kruzna": 1,
"opis1":"Jako lepa staza",
"opsirnije":"0",
"t_geojson":{},
"id_u_nizu": 99999
},
{
"id": 22,
"tip": "markirana",
"grupa": 2,
"ime": "PS_FGM_16_PripravnickiZapadni",
"gpxime": "PS_FGM_16_PripravnickiZapadni.gpx",
"oznaka": "FGMaraton_32.png",
"stil": "crvena_1",
"duzina": 1,
"tezina": 1,
"lepota": 1,
"uspon": 1,
"spust": 1,
"polazak": ["Popovica","Zmajevac"],
"mark": 1,
"bus": 1,
"bike": 1,
"kruzna": 1,
"opis1":"Jako lepa staza",
"opsirnije":"0",
"t_geojson":{},
"id_u_nizu": 99999
},
{
"id": 23,
"tip": "markirana",
"grupa": 2,
"ime": "PS_FGM_17_PripravnickiIstocni",
"gpxime": "PS_FGM_17_PripravnickiIstocni.gpx",
"oznaka": "FGMaraton_32.png",
"stil": "crvena_1",
"duzina": 1,
"tezina": 1,
"lepota": 1,
"uspon": 1,
"spust": 1,
"polazak": ["Popovica","Zmajevac"],
"mark": 1,
"bus": 1,
"bike": 1,
"kruzna": 1,
"opis1":"Jako lepa staza",
"opsirnije":"0",
"t_geojson":{},
"id_u_nizu": 99999
},
{
"id": 24,
"tip": "markirana",
"grupa": 2,
"ime": "PS_FGM_18_PripravnickiMini",
"gpxime": "PS_FGM_18_PripravnickiMini.gpx",
"oznaka": "FGMaraton_32.png",
"stil": "crvena_1",
"duzina": 1,
"tezina": 1,
"lepota": 1,
"uspon": 1,
"spust": 1,
"polazak": ["Popovica","Zmajevac"],
"mark": 1,
"bus": 1,
"bike": 1,
"kruzna": 1,
"opis1":"Jako lepa staza",
"opsirnije":"0",
"t_geojson":{},
"id_u_nizu": 99999
},
{
"id": 25,
"tip": "markirana",
"grupa": 2,
"ime": "PS_FGM_19_RadostZadovoljstvo",
"gpxime": "PS_FGM_19_RadostZadovoljstvo.gpx",
"oznaka": "FGMaraton_32.png",
"stil": "crvena_1",
"duzina": 1,
"tezina": 1,
"lepota": 1,
"uspon": 1,
"spust": 1,
"polazak": ["Popovica","Zmajevac"],
"mark": 1,
"bus": 1,
"bike": 1,
"kruzna": 1,
"opis1":"Jako lepa staza",
"opsirnije":"0",
"t_geojson":{},
"id_u_nizu": 99999
},
{
"id": 26,
"tip": "markirana",
"grupa": 2,
"ime": "PS_FruskaGora_Maraton_SveStaze&WP",
"gpxime": "PS_FruskaGora_Maraton_SveStaze&WP.gpx",
"oznaka": "FGMaraton_32.png",
"stil": "crvena_1",
"duzina": 1,
"tezina": 1,
"lepota": 1,
"uspon": 1,
"spust": 1,
"polazak": ["Popovica","Zmajevac"],
"mark": 1,
"bus": 1,
"bike": 1,
"kruzna": 1,
"opis1":"Jako lepa staza",
"opsirnije":"0",
"t_geojson":{},
"id_u_nizu": 99999
},
{
"id": 27,
"tip": "markirana",
"grupa": 2,
"ime": "PS_FruskaGora_Maraton_SveStaze",
"gpxime": "PS_FruskaGora_Maraton_SveStaze.gpx",
"oznaka": "FGMaraton_32.png",
"stil": "crvena_1",
"duzina": 1,
"tezina": 1,
"lepota": 1,
"uspon": 1,
"spust": 1,
"polazak": ["Popovica","Zmajevac"],
"mark": 1,
"bus": 1,
"bike": 1,
"kruzna": 1,
"opis1":"Jako lepa staza",
"opsirnije":"0",
"t_geojson":{},
"id_u_nizu": 99999
},
{
"id": 28,
"tip": "markirana",
"grupa": 2,
"ime": "PS_FruskaGora_Maraton_SviWP",
"gpxime": "PS_FruskaGora_Maraton_SviWP.gpx",
"oznaka": "FGMaraton_32.png",
"stil": "crvena_1",
"duzina": 1,
"tezina": 1,
"lepota": 1,
"uspon": 1,
"spust": 1,
"polazak": ["Popovica","Zmajevac"],
"mark": 1,
"bus": 1,
"bike": 1,
"kruzna": 1,
"opis1":"Jako lepa staza",
"opsirnije":"0",
"t_geojson":{},
"id_u_nizu": 99999
},
{
"id": 29,
"tip": "markirana",
"grupa": 3,
"ime": "PS_BM_01_Veliki",
"gpxime": "PS_BM_01_Veliki.gpx",
"oznaka": "BMaraton_32.png",
"stil": "crvena_2",
"duzina": 1,
"tezina": 1,
"lepota": 1,
"uspon": 1,
"spust": 1,
"polazak": ["Popovica","Zmajevac"],
"mark": 1,
"bus": 1,
"bike": 1,
"kruzna": 1,
"opis1":"Jako lepa staza",
"opsirnije":"0",
"t_geojson":{},
"id_u_nizu": 99999
},
{
"id": 30,
"tip": "markirana",
"grupa": 3,
"ime": "PS_BM_02_SrednjiZapadni",
"gpxime": "PS_BM_02_SrednjiZapadni.gpx",
"oznaka": "BMaraton_32.png",
"stil": "crvena_2",
"duzina": 1,
"tezina": 1,
"lepota": 1,
"uspon": 1,
"spust": 1,
"polazak": ["Popovica","Zmajevac"],
"mark": 1,
"bus": 1,
"bike": 1,
"kruzna": 1,
"opis1":"Jako lepa staza",
"opsirnije":"0",
"t_geojson":{},
"id_u_nizu": 99999
},
{
"id": 31,
"tip": "markirana",
"grupa": 3,
"ime": "PS_BM_03_SrednjiIstocni",
"gpxime": "PS_BM_03_SrednjiIstocni.gpx",
"oznaka": "BMaraton_32.png",
"stil": "crvena_2",
"duzina": 1,
"tezina": 1,
"lepota": 1,
"uspon": 1,
"spust": 1,
"polazak": ["Popovica","Zmajevac"],
"mark": 1,
"bus": 1,
"bike": 1,
"kruzna": 1,
"opis1":"Jako lepa staza",
"opsirnije":"0",
"t_geojson":{},
"id_u_nizu": 99999
},
{
"id": 32,
"tip": "markirana",
"grupa": 3,
"ime": "PS_BM_04_Mali",
"gpxime": "PS_BM_04_Mali.gpx",
"oznaka": "BMaraton_32.png",
"stil": "crvena_2",
"duzina": 1,
"tezina": 1,
"lepota": 1,
"uspon": 1,
"spust": 1,
"polazak": ["Popovica","Zmajevac"],
"mark": 1,
"bus": 1,
"bike": 1,
"kruzna": 1,
"opis1":"Jako lepa staza",
"opsirnije":"0",
"t_geojson":{},
"id_u_nizu": 99999
},
{
"id": 33,
"tip": "markirana",
"grupa": 3,
"ime": "PS_BM_05_Osnovni",
"gpxime": "PS_BM_05_Osnovni.gpx",
"oznaka": "BMaraton_32.png",
"stil": "crvena_2",
"duzina": 1,
"tezina": 1,
"lepota": 1,
"uspon": 1,
"spust": 1,
"polazak": ["Popovica","Zmajevac"],
"mark": 1,
"bus": 1,
"bike": 1,
"kruzna": 1,
"opis1":"Jako lepa staza",
"opsirnije":"0",
"t_geojson":{},
"id_u_nizu": 99999
},
{
"id": 34,
"tip": "markirana",
"grupa": 3,
"ime": "PS_BM_06_ZaNajmladje",
"gpxime": "PS_BM_06_ZaNajmladje.gpx",
"oznaka": "BMaraton_32.png",
"stil": "crvena_2",
"duzina": 1,
"tezina": 1,
"lepota": 1,
"uspon": 1,
"spust": 1,
"polazak": ["Popovica","Zmajevac"],
"mark": 1,
"bus": 1,
"bike": 1,
"kruzna": 1,
"opis1":"Jako lepa staza",
"opsirnije":"0",
"t_geojson":{},
"id_u_nizu": 99999
},
{
"id": 35,
"tip": "markirana",
"grupa": 3,
"ime": "PS_FruskaGora_BukovackiMaraton_SveStaze&WP",
"gpxime": "PS_FruskaGora_BukovackiMaraton_SveStaze&WP.gpx",
"oznaka": "BMaraton_32.png",
"stil": "crvena_2",
"duzina": 1,
"tezina": 1,
"lepota": 1,
"uspon": 1,
"spust": 1,
"polazak": ["Popovica","Zmajevac"],
"mark": 1,
"bus": 1,
"bike": 1,
"kruzna": 1,
"opis1":"Jako lepa staza",
"opsirnije":"0",
"t_geojson":{},
"id_u_nizu": 99999
},
{
"id": 36,
"tip": "markirana",
"grupa": 4,
"ime": "PS_FG_P01_Izvorska",
"gpxime": "PS_FG_P01_Izvorska.gpx",
"oznaka": "CrvenoBela_Kruznica_Standardna_32.png",
"stil": "crvena_3",
"duzina": 1,
"tezina": 1,
"lepota": 1,
"uspon": 1,
"spust": 1,
"polazak": ["Popovica","Zmajevac"],
"mark": 1,
"bus": 1,
"bike": 1,
"kruzna": 1,
"opis1":"Jako lepa staza",
"opsirnije":"0",
"t_geojson":{},
"id_u_nizu": 99999
},
{
"id": 37,
"tip": "markirana",
"grupa": 4,
"ime": "PS_FG_P02a_Vilenjacka1",
"gpxime": "PS_FG_P02a_Vilenjacka1.gpx",
"oznaka": "CrvenoPlava_Kruznica_Vilenjacka_32.png",
"stil": "crvena_3",
"duzina": 1,
"tezina": 1,
"lepota": 1,
"uspon": 1,
"spust": 1,
"polazak": ["Popovica","Zmajevac"],
"mark": 1,
"bus": 1,
"bike": 1,
"kruzna": 1,
"opis1":"Jako lepa staza",
"opsirnije":"0",
"t_geojson":{},
"id_u_nizu": 99999
},
{
"id": 38,
"tip": "markirana",
"grupa": 4,
"ime": "PS_FG_P02b_Vilenjacka2",
"gpxime": "PS_FG_P02b_Vilenjacka2.gpx",
"oznaka": "CrvenoPlava_Kruznica_Vilenjacka_32.png",
"stil": "crvena_3",
"duzina": 1,
"tezina": 1,
"lepota": 1,
"uspon": 1,
"spust": 1,
"polazak": ["Popovica","Zmajevac"],
"mark": 1,
"bus": 1,
"bike": 1,
"kruzna": 1,
"opis1":"Jako lepa staza",
"opsirnije":"0",
"t_geojson":{},
"id_u_nizu": 99999
},
{
"id": 39,
"tip": "markirana",
"grupa": 4,
"ime": "PS_FG_P02c_Vilenjacka3",
"gpxime": "PS_FG_P02c_Vilenjacka3.gpx",
"oznaka": "CrvenoPlava_Kruznica_Vilenjacka_32.png",
"stil": "crvena_3",
"duzina": 1,
"tezina": 1,
"lepota": 1,
"uspon": 1,
"spust": 1,
"polazak": ["Popovica","Zmajevac"],
"mark": 1,
"bus": 1,
"bike": 1,
"kruzna": 1,
"opis1":"Jako lepa staza",
"opsirnije":"0",
"t_geojson":{},
"id_u_nizu": 99999
},
{
"id": 40,
"tip": "markirana",
"grupa": 4,
"ime": "PS_FG_P03_Monaska",
"gpxime": "PS_FG_P03_Monaska.gpx",
"oznaka": "Monaska_32.png",
"stil": "crvena_3",
"duzina": 1,
"tezina": 1,
"lepota": 1,
"uspon": 1,
"spust": 1,
"polazak": ["Popovica","Zmajevac"],
"mark": 1,
"bus": 1,
"bike": 1,
"kruzna": 1,
"opis1":"Jako lepa staza",
"opsirnije":"0",
"t_geojson":{},
"id_u_nizu": 99999
},
{
"id": 41,
"tip": "markirana",
"grupa": 4,
"ime": "PS_FG_P04_Postarska",
"gpxime": "PS_FG_P04_Postarska.gpx",
"oznaka": "CrvenoBela_Kruznica_Standardna_32.png",
"stil": "crvena_3",
"duzina": 1,
"tezina": 1,
"lepota": 1,
"uspon": 1,
"spust": 1,
"polazak": ["Popovica","Zmajevac"],
"mark": 1,
"bus": 1,
"bike": 1,
"kruzna": 1,
"opis1":"Jako lepa staza",
"opsirnije":"0",
"t_geojson":{},
"id_u_nizu": 99999
},
{
"id": 42,
"tip": "markirana",
"grupa": 4,
"ime": "PS_FG_P05_Lazina",
"gpxime": "PS_FG_P05_Lazina.gpx",
"oznaka": "LazinaSaka_32.png",
"stil": "crvena_3",
"duzina": 1,
"tezina": 1,
"lepota": 1,
"uspon": 1,
"spust": 1,
"polazak": ["Popovica","Zmajevac"],
"mark": 1,
"bus": 1,
"bike": 1,
"kruzna": 1,
"opis1":"Jako lepa staza",
"opsirnije":"0",
"t_geojson":{},
"id_u_nizu": 99999
},
{
"id": 43,
"tip": "markirana",
"grupa": 4,
"ime": "PS_FG_P06_Brankovac-CrveniCot",
"gpxime": "PS_FG_P06_Brankovac-CrveniCot.gpx",
"oznaka": "CrvenoBela_Kruznica_Standardna_32.png",
"stil": "crvena_3",
"duzina": 1,
"tezina": 1,
"lepota": 1,
"uspon": 1,
"spust": 1,
"polazak": ["Popovica","Zmajevac"],
"mark": 1,
"bus": 1,
"bike": 1,
"kruzna": 1,
"opis1":"Jako lepa staza",
"opsirnije":"0",
"t_geojson":{},
"id_u_nizu": 99999
},
{
"id": 44,
"tip": "markirana",
"grupa": 4,
"ime": "PS_FG_P07_Partizanska",
"gpxime": "PS_FG_P07_Partizanska.gpx",
"oznaka": "Petokraka_Partizanska_32.png",
"stil": "crvena_3",
"duzina": 1,
"tezina": 1,
"lepota": 1,
"uspon": 1,
"spust": 1,
"polazak": ["Popovica","Zmajevac"],
"mark": 1,
"bus": 1,
"bike": 1,
"kruzna": 1,
"opis1":"Jako lepa staza",
"opsirnije":"0",
"t_geojson":{},
"id_u_nizu": 99999
},
{
"id": 45,
"tip": "markirana",
"grupa": 4,
"ime": "PS_FG_P08_GradacSenderoLuminoso",
"gpxime": "PS_FG_P08_GradacSenderoLuminoso.gpx",
"oznaka": "FluoZelenoNarandzasta_32.png",
"stil": "crvena_3",
"duzina": 1,
"tezina": 1,
"lepota": 1,
"uspon": 1,
"spust": 1,
"polazak": ["Popovica","Zmajevac"],
"mark": 1,
"bus": 1,
"bike": 1,
"kruzna": 1,
"opis1":"Jako lepa staza",
"opsirnije":"0",
"t_geojson":{},
"id_u_nizu": 99999
},
{
"id": 46,
"tip": "markirana",
"grupa": 4,
"ime": "PS_FG_SZ01_PopovicaPlava",
"gpxime": "PS_FG_SZ01_PopovicaPlava.gpx",
"oznaka": "PlavaTacka_32.png",
"stil": "crvena_3",
"duzina": 1,
"tezina": 1,
"lepota": 1,
"uspon": 1,
"spust": 1,
"polazak": ["Popovica","Zmajevac"],
"mark": 1,
"bus": 1,
"bike": 1,
"kruzna": 1,
"opis1":"Jako lepa staza",
"opsirnije":"0",
"t_geojson":{},
"id_u_nizu": 99999
},
{
"id": 47,
"tip": "markirana",
"grupa": 4,
"ime": "PS_FG_SZ02_PopovicaZelena",
"gpxime": "PS_FG_SZ02_PopovicaZelena.gpx",
"oznaka": "ZelenaTacka_32.png",
"stil": "crvena_3",
"duzina": 1,
"tezina": 1,
"lepota": 1,
"uspon": 1,
"spust": 1,
"polazak": ["Popovica","Zmajevac"],
"mark": 1,
"bus": 1,
"bike": 1,
"kruzna": 1,
"opis1":"Jako lepa staza",
"opsirnije":"0",
"t_geojson":{},
"id_u_nizu": 99999
},
{
"id": 48,
"tip": "markirana",
"grupa": 4,
"ime": "PS_FG_SZ03_StrazilovoZelena",
"gpxime": "PS_FG_SZ03_StrazilovoZelena.gpx",
"oznaka": "ZelenaTacka_32.png",
"stil": "crvena_3",
"duzina": 1,
"tezina": 1,
"lepota": 1,
"uspon": 1,
"spust": 1,
"polazak": ["Popovica","Zmajevac"],
"mark": 1,
"bus": 1,
"bike": 1,
"kruzna": 1,
"opis1":"Jako lepa staza",
"opsirnije":"0",
"t_geojson":{},
"id_u_nizu": 99999
},
{
"id": 49,
"tip": "markirana",
"grupa": 4,
"ime": "PS_FG_SZ05_Osovlje2_Duza",
"gpxime": "PS_FG_SZ05_Osovlje2_Duza.gpx",
"oznaka": "CrvenoBela_Kruznica_Standardna_32.png",
"stil": "crvena_3",
"duzina": 1,
"tezina": 1,
"lepota": 1,
"uspon": 1,
"spust": 1,
"polazak": ["Popovica","Zmajevac"],
"mark": 1,
"bus": 1,
"bike": 1,
"kruzna": 1,
"opis1":"Jako lepa staza",
"opsirnije":"0",
"t_geojson":{},
"id_u_nizu": 99999
},
{
"id": 50,
"tip": "markirana",
"grupa": 4,
"ime": "PS_FG_SZ06_Osovlje1_Kraca",
"gpxime": "PS_FG_SZ06_Osovlje1_Kraca.gpx",
"oznaka": "CrvenoBela_Kruznica_Standardna_32.png",
"stil": "crvena_3",
"duzina": 1,
"tezina": 1,
"lepota": 1,
"uspon": 1,
"spust": 1,
"polazak": ["Popovica","Zmajevac"],
"mark": 1,
"bus": 1,
"bike": 1,
"kruzna": 1,
"opis1":"Jako lepa staza",
"opsirnije":"0",
"t_geojson":{},
"id_u_nizu": 99999
},
{
"id": 51,
"tip": "markirana",
"grupa": 4,
"ime": "PS_FG_SZ07_Morintovo",
"gpxime": "PS_FG_SZ07_Morintovo.gpx",
"oznaka": "CrvenoBela_Kruznica_Standardna_32.png",
"stil": "crvena_3",
"duzina": 1,
"tezina": 1,
"lepota": 1,
"uspon": 1,
"spust": 1,
"polazak": ["Popovica","Zmajevac"],
"mark": 1,
"bus": 1,
"bike": 1,
"kruzna": 1,
"opis1":"Jako lepa staza",
"opsirnije":"0",
"t_geojson":{},
"id_u_nizu": 99999
},
{
"id": 52,
"tip": "markirana",
"grupa": 5,
"ime": "PS_FG_M07(braon)_ZimskaSluzba-Norcev",
"gpxime": "PS_FG_M07(braon)_ZimskaSluzba-Norcev.gpx",
"oznaka": "Braon_32.png",
"stil": "braon_0",
"duzina": 1,
"tezina": 1,
"lepota": 1,
"uspon": 1,
"spust": 1,
"polazak": ["Popovica","Zmajevac"],
"mark": 1,
"bus": 1,
"bike": 1,
"kruzna": 1,
"opis1":"Jako lepa staza",
"opsirnije":"0",
"t_geojson":{},
"id_u_nizu": 99999
},
{
"id": 53,
"tip": "markirana",
"grupa": 5,
"ime": "PS_FG_M10(braon)_PDVojvodina-NovoHopovo-StaroHopovo-PartizanskiPut",
"gpxime": "PS_FG_M10(braon)_PDVojvodina-NovoHopovo-StaroHopovo-PartizanskiPut.gpx",
"oznaka": "Braon_32.png",
"stil": "braon_0",
"duzina": 1,
"tezina": 1,
"lepota": 1,
"uspon": 1,
"spust": 1,
"polazak": ["Popovica","Zmajevac"],
"mark": 1,
"bus": 1,
"bike": 1,
"kruzna": 1,
"opis1":"Jako lepa staza",
"opsirnije":"0",
"t_geojson":{},
"id_u_nizu": 99999
},
{
"id": 54,
"tip": "markirana",
"grupa": 5,
"ime": "PS_FG_M22(braon)_Cerevic-KatanskeLivade-Isajlovac",
"gpxime": "PS_FG_M22(braon)_Cerevic-KatanskeLivade-Isajlovac.gpx",
"oznaka": "Braon_32.png",
"stil": "braon_0",
"duzina": 1,
"tezina": 1,
"lepota": 1,
"uspon": 1,
"spust": 1,
"polazak": ["Popovica","Zmajevac"],
"mark": 1,
"bus": 1,
"bike": 1,
"kruzna": 1,
"opis1":"Jako lepa staza",
"opsirnije":"0",
"t_geojson":{},
"id_u_nizu": 99999
},
{
"id": 55,
"tip": "markirana",
"grupa": 6,
"ime": "PS_FG_M04(crna)_Glavica-VilinaVodica-Strazilovo",
"gpxime": "PS_FG_M04(crna)_Glavica-VilinaVodica-Strazilovo.gpx",
"oznaka": "Crna_32.png",
"stil": "crna_0",
"duzina": 1,
"tezina": 1,
"lepota": 1,
"uspon": 1,
"spust": 1,
"polazak": ["Popovica","Zmajevac"],
"mark": 1,
"bus": 1,
"bike": 1,
"kruzna": 1,
"opis1":"Jako lepa staza",
"opsirnije":"0",
"t_geojson":{},
"id_u_nizu": 99999
},
{
"id": 56,
"tip": "markirana",
"grupa": 6,
"ime": "PS_FG_M08(crna)_ZimskaSluzba-TVtoranj",
"gpxime": "PS_FG_M08(crna)_ZimskaSluzba-TVtoranj.gpx",
"oznaka": "Crna_32.png",
"stil": "crna_0",
"duzina": 1,
"tezina": 1,
"lepota": 1,
"uspon": 1,
"spust": 1,
"polazak": ["Popovica","Zmajevac"],
"mark": 1,
"bus": 1,
"bike": 1,
"kruzna": 1,
"opis1":"Jako lepa staza",
"opsirnije":"0",
"t_geojson":{},
"id_u_nizu": 99999
},
{
"id": 57,
"tip": "markirana",
"grupa": 6,
"ime": "PS_FG_M21(crna)_Cerevic-KozjeBrdo-Osovlje",
"gpxime": "PS_FG_M21(crna)_Cerevic-KozjeBrdo-Osovlje.gpx",
"oznaka": "Crna_32.png",
"stil": "crna_0",
"duzina": 1,
"tezina": 1,
"lepota": 1,
"uspon": 1,
"spust": 1,
"polazak": ["Popovica","Zmajevac"],
"mark": 1,
"bus": 1,
"bike": 1,
"kruzna": 1,
"opis1":"Jako lepa staza",
"opsirnije":"0",
"t_geojson":{},
"id_u_nizu": 99999
},
{
"id": 58,
"tip": "markirana",
"grupa": 6,
"ime": "PS_FG_M32(crna)_Stranputica-Gredelj",
"gpxime": "PS_FG_M32(crna)_Stranputica-Gredelj.gpx",
"oznaka": "Crna_32.png",
"stil": "crna_0",
"duzina": 1,
"tezina": 1,
"lepota": 1,
"uspon": 1,
"spust": 1,
"polazak": ["Popovica","Zmajevac"],
"mark": 1,
"bus": 1,
"bike": 1,
"kruzna": 1,
"opis1":"Jako lepa staza",
"opsirnije":"0",
"t_geojson":{},
"id_u_nizu": 99999
},
{
"id": 59,
"tip": "markirana",
"grupa": 7,
"ime": "PS_FG_M02(crvena)_Strazilovo-ManastirGrgrteg",
"gpxime": "PS_FG_M02(crvena)_Strazilovo-ManastirGrgrteg.gpx",
"oznaka": "Crvena_32.png",
"stil": "crvena_4",
"duzina": 1,
"tezina": 1,
"lepota": 1,
"uspon": 1,
"spust": 1,
"polazak": ["Popovica","Zmajevac"],
"mark": 1,
"bus": 1,
"bike": 1,
"kruzna": 1,
"opis1":"Jako lepa staza",
"opsirnije":"0",
"t_geojson":{},
"id_u_nizu": 99999
},
{
"id": 60,
"tip": "markirana",
"grupa": 7,
"ime": "PS_FG_M05(crvena)_ZimskaSluzba-VilinaVodica-Bukovac",
"gpxime": "PS_FG_M05(crvena)_ZimskaSluzba-VilinaVodica-Bukovac.gpx",
"oznaka": "Crvena_32.png",
"stil": "crvena_4",
"duzina": 1,
"tezina": 1,
"lepota": 1,
"uspon": 1,
"spust": 1,
"polazak": ["Popovica","Zmajevac"],
"mark": 1,
"bus": 1,
"bike": 1,
"kruzna": 1,
"opis1":"Jako lepa staza",
"opsirnije":"0",
"t_geojson":{},
"id_u_nizu": 99999
},
{
"id": 61,
"tip": "markirana",
"grupa": 7,
"ime": "PS_FG_M16(crvena)_InstitutVenac-Morintovo-ManastirRavanica",
"gpxime": "PS_FG_M16(crvena)_InstitutVenac-Morintovo-ManastirRavanica.gpx",
"oznaka": "Crvena_32.png",
"stil": "crvena_4",
"duzina": 1,
"tezina": 1,
"lepota": 1,
"uspon": 1,
"spust": 1,
"polazak": ["Popovica","Zmajevac"],
"mark": 1,
"bus": 1,
"bike": 1,
"kruzna": 1,
"opis1":"Jako lepa staza",
"opsirnije":"0",
"t_geojson":{},
"id_u_nizu": 99999
},
{
"id": 62,
"tip": "markirana",
"grupa": 7,
"ime": "PS_FG_M18(crvena)_St.Ledinci-Kamenolom-Zmajevac",
"gpxime": "PS_FG_M18(crvena)_St.Ledinci-Kamenolom-Zmajevac.gpx",
"oznaka": "Crvena_32.png",
"stil": "crvena_4",
"duzina": 1,
"tezina": 1,
"lepota": 1,
"uspon": 1,
"spust": 1,
"polazak": ["Popovica","Zmajevac"],
"mark": 1,
"bus": 1,
"bike": 1,
"kruzna": 1,
"opis1":"Jako lepa staza",
"opsirnije":"0",
"t_geojson":{},
"id_u_nizu": 99999
},
{
"id": 63,
"tip": "markirana",
"grupa": 7,
"ime": "PS_FG_M25(crvena)_ManastirBeocin-Osovlje-PavlasovCot",
"gpxime": "PS_FG_M25(crvena)_ManastirBeocin-Osovlje-PavlasovCot.gpx",
"oznaka": "Crvena_32.png",
"stil": "crvena_4",
"duzina": 1,
"tezina": 1,
"lepota": 1,
"uspon": 1,
"spust": 1,
"polazak": ["Popovica","Zmajevac"],
"mark": 1,
"bus": 1,
"bike": 1,
"kruzna": 1,
"opis1":"Jako lepa staza",
"opsirnije":"0",
"t_geojson":{},
"id_u_nizu": 99999
},
{
"id": 64,
"tip": "markirana",
"grupa": 7,
"ime": "PS_FG_M26(crvena)_ManastirBeocin-Brankovac",
"gpxime": "PS_FG_M26(crvena)_ManastirBeocin-Brankovac.gpx",
"oznaka": "Crvena_32.png",
"stil": "crvena_4",
"duzina": 1,
"tezina": 1,
"lepota": 1,
"uspon": 1,
"spust": 1,
"polazak": ["Popovica","Zmajevac"],
"mark": 1,
"bus": 1,
"bike": 1,
"kruzna": 1,
"opis1":"Jako lepa staza",
"opsirnije":"0",
"t_geojson":{},
"id_u_nizu": 99999
},
{
"id": 65,
"tip": "markirana",
"grupa": 7,
"ime": "PS_FG_M33(crvena2)_KraljevaStolicaKT-LazinVir",
"gpxime": "PS_FG_M33(crvena2)_KraljevaStolicaKT-LazinVir.gpx",
"oznaka": "Crvena_32.png",
"stil": "crvena_4",
"duzina": 1,
"tezina": 1,
"lepota": 1,
"uspon": 1,
"spust": 1,
"polazak": ["Popovica","Zmajevac"],
"mark": 1,
"bus": 1,
"bike": 1,
"kruzna": 1,
"opis1":"Jako lepa staza",
"opsirnije":"0",
"t_geojson":{},
"id_u_nizu": 99999
},
{
"id": 66,
"tip": "markirana",
"grupa": 7,
"ime": "PS_FG_M34(crvena)_IzvorKucurinaVrdnik-PDomZmajevac",
"gpxime": "PS_FG_M34(crvena)_IzvorKucurinaVrdnik-PDomZmajevac.gpx",
"oznaka": "Crvena_32.png",
"stil": "crvena_4",
"duzina": 1,
"tezina": 1,
"lepota": 1,
"uspon": 1,
"spust": 1,
"polazak": ["Popovica","Zmajevac"],
"mark": 1,
"bus": 1,
"bike": 1,
"kruzna": 1,
"opis1":"Jako lepa staza",
"opsirnije":"0",
"t_geojson":{},
"id_u_nizu": 99999
},
{
"id": 67,
"tip": "markirana",
"grupa": 8,
"ime": "PS_FG_M01(plava)_Strazilovo-VelikaRemeta-Grgeteg-TVtoranj",
"gpxime": "PS_FG_M01(plava)_Strazilovo-VelikaRemeta-Grgeteg-TVtoranj.gpx",
"oznaka": "Plava_32.png",
"stil": "plava_0",
"duzina": 1,
"tezina": 1,
"lepota": 1,
"uspon": 1,
"spust": 1,
"polazak": ["Popovica","Zmajevac"],
"mark": 1,
"bus": 1,
"bike": 1,
"kruzna": 1,
"opis1":"Jako lepa staza",
"opsirnije":"0",
"t_geojson":{},
"id_u_nizu": 99999
},
{
"id": 68,
"tip": "markirana",
"grupa": 8,
"ime": "PS_FG_M09(plava)_Hangar-VenacSpomenikNOB",
"gpxime": "PS_FG_M09(plava)_Hangar-VenacSpomenikNOB.gpx",
"oznaka": "Plava_32.png",
"stil": "plava_0",
"duzina": 1,
"tezina": 1,
"lepota": 1,
"uspon": 1,
"spust": 1,
"polazak": ["Popovica","Zmajevac"],
"mark": 1,
"bus": 1,
"bike": 1,
"kruzna": 1,
"opis1":"Jako lepa staza",
"opsirnije":"0",
"t_geojson":{},
"id_u_nizu": 99999
},
{
"id": 69,
"tip": "markirana",
"grupa": 8,
"ime": "PS_FG_M20(plava)_ManastirJazak-Brankovac",
"gpxime": "PS_FG_M20(plava)_ManastirJazak-Brankovac.gpx",
"oznaka": "Plava_32.png",
"stil": "plava_0",
"duzina": 1,
"tezina": 1,
"lepota": 1,
"uspon": 1,
"spust": 1,
"polazak": ["Popovica","Zmajevac"],
"mark": 1,
"bus": 1,
"bike": 1,
"kruzna": 1,
"opis1":"Jako lepa staza",
"opsirnije":"0",
"t_geojson":{},
"id_u_nizu": 99999
},
{
"id": 70,
"tip": "markirana",
"grupa": 8,
"ime": "PS_FG_M24(plava)_StariRakovac-Vadjevine",
"gpxime": "PS_FG_M24(plava)_StariRakovac-Vadjevine.gpx",
"oznaka": "Plava_32.png",
"stil": "plava_0",
"duzina": 1,
"tezina": 1,
"lepota": 1,
"uspon": 1,
"spust": 1,
"polazak": ["Popovica","Zmajevac"],
"mark": 1,
"bus": 1,
"bike": 1,
"kruzna": 1,
"opis1":"Jako lepa staza",
"opsirnije":"0",
"t_geojson":{},
"id_u_nizu": 99999
},
{
"id": 71,
"tip": "markirana",
"grupa": 8,
"ime": "PS_FG_M29(plava)_Letenka-Grabovacki(Crni)Vodopad",
"gpxime": "PS_FG_M29(plava)_Letenka-Grabovacki(Crni)Vodopad.gpx",
"oznaka": "Plava_32.png",
"stil": "plava_0",
"duzina": 1,
"tezina": 1,
"lepota": 1,
"uspon": 1,
"spust": 1,
"polazak": ["Popovica","Zmajevac"],
"mark": 1,
"bus": 1,
"bike": 1,
"kruzna": 1,
"opis1":"Jako lepa staza",
"opsirnije":"0",
"t_geojson":{},
"id_u_nizu": 99999
},
{
"id": 72,
"tip": "markirana",
"grupa": 8,
"ime": "PS_FG_M30(plava)_Popradine-MasnaCupa",
"gpxime": "PS_FG_M30(plava)_Popradine-MasnaCupa.gpx",
"oznaka": "Plava_32.png",
"stil": "plava_0",
"duzina": 1,
"tezina": 1,
"lepota": 1,
"uspon": 1,
"spust": 1,
"polazak": ["Popovica","Zmajevac"],
"mark": 1,
"bus": 1,
"bike": 1,
"kruzna": 1,
"opis1":"Jako lepa staza",
"opsirnije":"0",
"t_geojson":{},
"id_u_nizu": 99999
},
{
"id": 73,
"tip": "markirana",
"grupa": 8,
"ime": "PS_FG_M31(plava)_Stranputica-CrveniCot",
"gpxime": "PS_FG_M31(plava)_Stranputica-CrveniCot.gpx",
"oznaka": "Plava_32.png",
"stil": "plava_0",
"duzina": 1,
"tezina": 1,
"lepota": 1,
"uspon": 1,
"spust": 1,
"polazak": ["Popovica","Zmajevac"],
"mark": 1,
"bus": 1,
"bike": 1,
"kruzna": 1,
"opis1":"Jako lepa staza",
"opsirnije":"0",
"t_geojson":{},
"id_u_nizu": 99999
},
{
"id": 74,
"tip": "markirana",
"grupa": 9,
"ime": "PS_FG_M06(zelena)_Paragovo-Glavica-Astal-TVtoranj",
"gpxime": "PS_FG_M06(zelena)_Paragovo-Glavica-Astal-TVtoranj.gpx",
"oznaka": "Zelena_32.png",
"stil": "zelena_0",
"duzina": 1,
"tezina": 1,
"lepota": 1,
"uspon": 1,
"spust": 1,
"polazak": ["Popovica","Zmajevac"],
"mark": 1,
"bus": 1,
"bike": 1,
"kruzna": 1,
"opis1":"Jako lepa staza",
"opsirnije":"0",
"t_geojson":{},
"id_u_nizu": 99999
},
{
"id": 75,
"tip": "markirana",
"grupa": 9,
"ime": "PS_FG_M11(zelena)_Hangar-VenacSpomenikNOB",
"gpxime": "PS_FG_M11(zelena)_Hangar-VenacSpomenikNOB.gpx",
"oznaka": "Zelena_32.png",
"stil": "zelena_0",
"duzina": 1,
"tezina": 1,
"lepota": 1,
"uspon": 1,
"spust": 1,
"polazak": ["Popovica","Zmajevac"],
"mark": 1,
"bus": 1,
"bike": 1,
"kruzna": 1,
"opis1":"Jako lepa staza",
"opsirnije":"0",
"t_geojson":{},
"id_u_nizu": 99999
},
{
"id": 76,
"tip": "markirana",
"grupa": 9,
"ime": "PS_FG_M12(zelena)_Vrdnik-Kula",
"gpxime": "PS_FG_M12(zelena)_Vrdnik-Kula.gpx",
"oznaka": "Zelena_32.png",
"stil": "zelena_0",
"duzina": 1,
"tezina": 1,
"lepota": 1,
"uspon": 1,
"spust": 1,
"polazak": ["Popovica","Zmajevac"],
"mark": 1,
"bus": 1,
"bike": 1,
"kruzna": 1,
"opis1":"Jako lepa staza",
"opsirnije":"0",
"t_geojson":{},
"id_u_nizu": 99999
},
{
"id": 77,
"tip": "markirana",
"grupa": 9,
"ime": "PS_FG_M14(zelena)_IzvorZvecan-PartizanskiPut",
"gpxime": "PS_FG_M14(zelena)_IzvorZvecan-PartizanskiPut.gpx",
"oznaka": "Zelena_32.png",
"stil": "zelena_0",
"duzina": 1,
"tezina": 1,
"lepota": 1,
"uspon": 1,
"spust": 1,
"polazak": ["Popovica","Zmajevac"],
"mark": 1,
"bus": 1,
"bike": 1,
"kruzna": 1,
"opis1":"Jako lepa staza",
"opsirnije":"0",
"t_geojson":{},
"id_u_nizu": 99999
},
{
"id": 78,
"tip": "markirana",
"grupa": 10,
"ime": "PS_FG_M03(zuta)_ManastirGrgeteg-Neradin-TVtoranj",
"gpxime": "PS_FG_M03(zuta)_ManastirGrgeteg-Neradin-TVtoranj.gpx",
"oznaka": "Zuta_32.png",
"stil": "zuta_0",
"duzina": 1,
"tezina": 1,
"lepota": 1,
"uspon": 1,
"spust": 1,
"polazak": ["Popovica","Zmajevac"],
"mark": 1,
"bus": 1,
"bike": 1,
"kruzna": 1,
"opis1":"Jako lepa staza",
"opsirnije":"0",
"t_geojson":{},
"id_u_nizu": 99999
},
{
"id": 79,
"tip": "markirana",
"grupa": 10,
"ime": "PS_FG_M13(zuta)_PutZaVenac-Vaga-Zvecan-Jezero",
"gpxime": "PS_FG_M13(zuta)_PutZaVenac-Vaga-Zvecan-Jezero.gpx",
"oznaka": "Zuta_32.png",
"stil": "zuta_0",
"duzina": 1,
"tezina": 1,
"lepota": 1,
"uspon": 1,
"spust": 1,
"polazak": ["Popovica","Zmajevac"],
"mark": 1,
"bus": 1,
"bike": 1,
"kruzna": 1,
"opis1":"Jako lepa staza",
"opsirnije":"0",
"t_geojson":{},
"id_u_nizu": 99999
},
{
"id": 80,
"tip": "markirana",
"grupa": 10,
"ime": "PS_FG_M17(zuta)_VrdnikTermal-PartizanskiPut",
"gpxime": "PS_FG_M17(zuta)_VrdnikTermal-PartizanskiPut.gpx",
"oznaka": "Zuta_32.png",
"stil": "zuta_0",
"duzina": 1,
"tezina": 1,
"lepota": 1,
"uspon": 1,
"spust": 1,
"polazak": ["Popovica","Zmajevac"],
"mark": 1,
"bus": 1,
"bike": 1,
"kruzna": 1,
"opis1":"Jako lepa staza",
"opsirnije":"0",
"t_geojson":{},
"id_u_nizu": 99999
},
{
"id": 81,
"tip": "markirana",
"grupa": 10,
"ime": "PS_FG_M19(zuta)_Rakovac-Kesten-Plana-Zmajevac",
"gpxime": "PS_FG_M19(zuta)_Rakovac-Kesten-Plana-Zmajevac.gpx",
"oznaka": "Zuta_32.png",
"stil": "zuta_0",
"duzina": 1,
"tezina": 1,
"lepota": 1,
"uspon": 1,
"spust": 1,
"polazak": ["Popovica","Zmajevac"],
"mark": 1,
"bus": 1,
"bike": 1,
"kruzna": 1,
"opis1":"Jako lepa staza",
"opsirnije":"0",
"t_geojson":{},
"id_u_nizu": 99999
},
{
"id": 82,
"tip": "markirana",
"grupa": 10,
"ime": "PS_FG_M23(zuta)_Testera-CrveniCot-PavlasovCot",
"gpxime": "PS_FG_M23(zuta)_Testera-CrveniCot-PavlasovCot.gpx",
"oznaka": "Zuta_32.png",
"stil": "zuta_0",
"duzina": 1,
"tezina": 1,
"lepota": 1,
"uspon": 1,
"spust": 1,
"polazak": ["Popovica","Zmajevac"],
"mark": 1,
"bus": 1,
"bike": 1,
"kruzna": 1,
"opis1":"Jako lepa staza",
"opsirnije":"0",
"t_geojson":{},
"id_u_nizu": 99999
},
{
"id": 83,
"tip": "markirana",
"grupa": 10,
"ime": "PS_FG_M27(zuta)_ManastirBeocin-IsinCot",
"gpxime": "PS_FG_M27(zuta)_ManastirBeocin-IsinCot.gpx",
"oznaka": "Zuta_32.png",
"stil": "zuta_0",
"duzina": 1,
"tezina": 1,
"lepota": 1,
"uspon": 1,
"spust": 1,
"polazak": ["Popovica","Zmajevac"],
"mark": 1,
"bus": 1,
"bike": 1,
"kruzna": 1,
"opis1":"Jako lepa staza",
"opsirnije":"0",
"t_geojson":{},
"id_u_nizu": 99999
},
{
"id": 84,
"tip": "markirana",
"grupa": 10,
"ime": "PS_FG_M28(zuta)_ManastirBeocin-Osovlje-DobriVodopad-OrlovskeStene",
"gpxime": "PS_FG_M28(zuta)_ManastirBeocin-Osovlje-DobriVodopad-OrlovskeStene.gpx",
"oznaka": "Zuta_32.png",
"stil": "zuta_0",
"duzina": 1,
"tezina": 1,
"lepota": 1,
"uspon": 1,
"spust": 1,
"polazak": ["Popovica","Zmajevac"],
"mark": 1,
"bus": 1,
"bike": 1,
"kruzna": 1,
"opis1":"Jako lepa staza",
"opsirnije":"0",
"t_geojson":{},
"id_u_nizu": 99999
},
{
"id": 85,
"tip": "markirana",
"grupa": 10,
"ime": "PS_FG_M36(zuta)_IsinCot-NadineKaskade",
"gpxime": "PS_FG_M36(zuta)_IsinCot-NadineKaskade.gpx",
"oznaka": "Zuta_32.png",
"stil": "zuta_0",
"duzina": 1,
"tezina": 1,
"lepota": 1,
"uspon": 1,
"spust": 1,
"polazak": ["Popovica","Zmajevac"],
"mark": 1,
"bus": 1,
"bike": 1,
"kruzna": 1,
"opis1":"Jako lepa staza",
"opsirnije":"0",
"t_geojson":{},
"id_u_nizu": 99999
},


 
        
			]
}	