var track_baza_1 = 
{
    "staze": [
{
"id": 3001,
"tip": "setnja",
"grupa": 1,
"ime": "PS_FG_CortanovackaTransverzala",
"gpxime": "PS_FG_CortanovackaTransverzala.gpx",
"oznaka": "CrvenoBela_Kruznica_Standardna_32.png",
"stil": "crvena_0",
"duzina": 1,
"tezina": 1,
"lepota": 1,
"uspon": 1,
"spust": 1,
"polazak": ["Popovica","Zmajevac"],
"mark": 1,
"bus": 1,
"bike": 1,
"kruzna": 1,
"opis1":"Jako lepa staza",
"opsirnije":"0",
"t_geojson":{},
"id_u_nizu": 99999
},
{
"id": 3002,
"tip": "setnja",
"grupa": 1,
"ime": "PS_FG_EvropskiPesackiPut_E7",
"gpxime": "PS_FG_EvropskiPesackiPut_E7.gpx",
"oznaka": "CrvenoZuta_Kruznica_E7_32.png",
"stil": "crvena_0",
"duzina": 1,
"tezina": 1,
"lepota": 1,
"uspon": 1,
"spust": 1,
"polazak": ["Popovica","Zmajevac"],
"mark": 1,
"bus": 1,
"bike": 1,
"kruzna": 1,
"opis1":"Jako lepa staza",
"opsirnije":"0",
"t_geojson":{},
"id_u_nizu": 99999
},
{
"id": 3003,
"tip": "setnja",
"grupa": 1,
"ime": "PS_FG_Transverzala",
"gpxime": "PS_FG_Transverzala.gpx",
"oznaka": "FGTransverzala_32.png",
"stil": "crvena_0",
"duzina": 1,
"tezina": 1,
"lepota": 1,
"uspon": 1,
"spust": 1,
"polazak": ["Popovica","Zmajevac"],
"mark": 1,
"bus": 1,
"bike": 1,
"kruzna": 1,
"opis1":"Jako lepa staza",
"opsirnije":"0",
"t_geojson":{},
"id_u_nizu": 99999
},
{
"id": 3004,
"tip": "setnja",
"grupa": 1,
"ime": "PS_FG_TransverzalaSremskiFront",
"gpxime": "PS_FG_TransverzalaSremskiFront.gpx",
"oznaka": "CrvenoBela_Kruznica_Standardna_32.png",
"stil": "crvena_0",
"duzina": 1,
"tezina": 1,
"lepota": 1,
"uspon": 1,
"spust": 1,
"polazak": ["Popovica","Zmajevac"],
"mark": 1,
"bus": 1,
"bike": 1,
"kruzna": 1,
"opis1":"Jako lepa staza",
"opsirnije":"0",
"t_geojson":{},
"id_u_nizu": 99999
},
{
"id": 3005,
"tip": "setnja",
"grupa": 1,
"ime": "PS_FG_VodopadskaTransverzala",
"gpxime": "PS_FG_VodopadskaTransverzala.gpx",
"oznaka": "Vodopadska_32.png",
"stil": "crvena_0",
"duzina": 1,
"tezina": 1,
"lepota": 1,
"uspon": 1,
"spust": 1,
"polazak": ["Popovica","Zmajevac"],
"mark": 1,
"bus": 1,
"bike": 1,
"kruzna": 1,
"opis1":"Jako lepa staza",
"opsirnije":"0",
"t_geojson":{},
"id_u_nizu": 99999
},
{
"id": 3006,
"tip": "setnja",
"grupa": 1,
"ime": "PS_FG_Zanatlijska",
"gpxime": "PS_FG_Zanatlijska.gpx",
"oznaka": "CrvenoBela_Kruznica_Standardna_32.png",
"stil": "crvena_0",
"duzina": 1,
"tezina": 1,
"lepota": 1,
"uspon": 1,
"spust": 1,
"polazak": ["Popovica","Zmajevac"],
"mark": 1,
"bus": 1,
"bike": 1,
"kruzna": 1,
"opis1":"Jako lepa staza",
"opsirnije":"0",
"t_geojson":{},
"id_u_nizu": 99999
},
{
"id": 3007,
"tip": "setnja",
"grupa": 2,
"ime": "PS_FGM_01_UltraEkstremni_UTMB4",
"gpxime": "PS_FGM_01_UltraEkstremni_UTMB4.gpx",
"oznaka": "FGMaraton_32.png",
"stil": "crvena_1",
"duzina": 1,
"tezina": 1,
"lepota": 1,
"uspon": 1,
"spust": 1,
"polazak": ["Popovica","Zmajevac"],
"mark": 1,
"bus": 1,
"bike": 1,
"kruzna": 1,
"opis1":"Jako lepa staza",
"opsirnije":"0",
"t_geojson":{},
"id_u_nizu": 99999
},
{
"id": 3008,
"tip": "setnja",
"grupa": 2,
"ime": "PS_FGM_02_Ultra_UTMB3",
"gpxime": "PS_FGM_02_Ultra_UTMB3.gpx",
"oznaka": "FGMaraton_32.png",
"stil": "crvena_1",
"duzina": 1,
"tezina": 1,
"lepota": 1,
"uspon": 1,
"spust": 1,
"polazak": ["Popovica","Zmajevac"],
"mark": 1,
"bus": 1,
"bike": 1,
"kruzna": 1,
"opis1":"Jako lepa staza",
"opsirnije":"0",
"t_geojson":{},
"id_u_nizu": 99999
},
{
"id": 3009,
"tip": "setnja",
"grupa": 2,
"ime": "PS_FGM_03_VelikiJuzni",
"gpxime": "PS_FGM_03_VelikiJuzni.gpx",
"oznaka": "FGMaraton_32.png",
"stil": "crvena_1",
"duzina": 1,
"tezina": 1,
"lepota": 1,
"uspon": 1,
"spust": 1,
"polazak": ["Popovica","Zmajevac"],
"mark": 1,
"bus": 1,
"bike": 1,
"kruzna": 1,
"opis1":"Jako lepa staza",
"opsirnije":"0",
"t_geojson":{},
"id_u_nizu": 99999
},
{
"id": 3010,
"tip": "setnja",
"grupa": 2,
"ime": "PS_FGM_04_VelikiZapadni",
"gpxime": "PS_FGM_04_VelikiZapadni.gpx",
"oznaka": "FGMaraton_32.png",
"stil": "crvena_1",
"duzina": 1,
"tezina": 1,
"lepota": 1,
"uspon": 1,
"spust": 1,
"polazak": ["Popovica","Zmajevac"],
"mark": 1,
"bus": 1,
"bike": 1,
"kruzna": 1,
"opis1":"Jako lepa staza",
"opsirnije":"0",
"t_geojson":{},
"id_u_nizu": 99999
},
{
"id": 3011,
"tip": "setnja",
"grupa": 2,
"ime": "PS_FGM_05_VelikiIstocni_UTMB2",
"gpxime": "PS_FGM_05_VelikiIstocni_UTMB2.gpx",
"oznaka": "FGMaraton_32.png",
"stil": "crvena_1",
"duzina": 1,
"tezina": 1,
"lepota": 1,
"uspon": 1,
"spust": 1,
"polazak": ["Popovica","Zmajevac"],
"mark": 1,
"bus": 1,
"bike": 1,
"kruzna": 1,
"opis1":"Jako lepa staza",
"opsirnije":"0",
"t_geojson":{},
"id_u_nizu": 99999
},
{
"id": 3012,
"tip": "setnja",
"grupa": 2,
"ime": "PS_FGM_06_SrednjiIstocni_UTMB1",
"gpxime": "PS_FGM_06_SrednjiIstocni_UTMB1.gpx",
"oznaka": "FGMaraton_32.png",
"stil": "crvena_1",
"duzina": 1,
"tezina": 1,
"lepota": 1,
"uspon": 1,
"spust": 1,
"polazak": ["Popovica","Zmajevac"],
"mark": 1,
"bus": 1,
"bike": 1,
"kruzna": 1,
"opis1":"Jako lepa staza",
"opsirnije":"0",
"t_geojson":{},
"id_u_nizu": 99999
},
{
"id": 3013,
"tip": "setnja",
"grupa": 2,
"ime": "PS_FGM_07_SrednjiZapadni",
"gpxime": "PS_FGM_07_SrednjiZapadni.gpx",
"oznaka": "FGMaraton_32.png",
"stil": "crvena_1",
"duzina": 1,
"tezina": 1,
"lepota": 1,
"uspon": 1,
"spust": 1,
"polazak": ["Popovica","Zmajevac"],
"mark": 1,
"bus": 1,
"bike": 1,
"kruzna": 1,
"opis1":"Jako lepa staza",
"opsirnije":"0",
"t_geojson":{},
"id_u_nizu": 99999
},
{
"id": 3014,
"tip": "setnja",
"grupa": 2,
"ime": "PS_FGM_08_SrednjiJuzni",
"gpxime": "PS_FGM_08_SrednjiJuzni.gpx",
"oznaka": "FGMaraton_32.png",
"stil": "crvena_1",
"duzina": 1,
"tezina": 1,
"lepota": 1,
"uspon": 1,
"spust": 1,
"polazak": ["Popovica","Zmajevac"],
"mark": 1,
"bus": 1,
"bike": 1,
"kruzna": 1,
"opis1":"Jako lepa staza",
"opsirnije":"0",
"t_geojson":{},
"id_u_nizu": 99999
},
{
"id": 3015,
"tip": "setnja",
"grupa": 2,
"ime": "PS_FGM_09_MaliIstocniEkstremni",
"gpxime": "PS_FGM_09_MaliIstocniEkstremni.gpx",
"oznaka": "FGMaraton_32.png",
"stil": "crvena_1",
"duzina": 1,
"tezina": 1,
"lepota": 1,
"uspon": 1,
"spust": 1,
"polazak": ["Popovica","Zmajevac"],
"mark": 1,
"bus": 1,
"bike": 1,
"kruzna": 1,
"opis1":"Jako lepa staza",
"opsirnije":"0",
"t_geojson":{},
"id_u_nizu": 99999
},
{
"id": 3016,
"tip": "setnja",
"grupa": 2,
"ime": "PS_FGM_10_MaliZapadniEkstremni",
"gpxime": "PS_FGM_10_MaliZapadniEkstremni.gpx",
"oznaka": "FGMaraton_32.png",
"stil": "crvena_1",
"duzina": 1,
"tezina": 1,
"lepota": 1,
"uspon": 1,
"spust": 1,
"polazak": ["Popovica","Zmajevac"],
"mark": 1,
"bus": 1,
"bike": 1,
"kruzna": 1,
"opis1":"Jako lepa staza",
"opsirnije":"0",
"t_geojson":{},
"id_u_nizu": 99999
},
{
"id": 3017,
"tip": "setnja",
"grupa": 2,
"ime": "PS_FGM_11_MaliZapadni",
"gpxime": "PS_FGM_11_MaliZapadni.gpx",
"oznaka": "FGMaraton_32.png",
"stil": "crvena_1",
"duzina": 1,
"tezina": 1,
"lepota": 1,
"uspon": 1,
"spust": 1,
"polazak": ["Popovica","Zmajevac"],
"mark": 1,
"bus": 1,
"bike": 1,
"kruzna": 1,
"opis1":"Jako lepa staza",
"opsirnije":"0",
"t_geojson":{},
"id_u_nizu": 99999
},
{
"id": 3018,
"tip": "setnja",
"grupa": 2,
"ime": "PS_FGM_12_MaliIstocni",
"gpxime": "PS_FGM_12_MaliIstocni.gpx",
"oznaka": "FGMaraton_32.png",
"stil": "crvena_1",
"duzina": 1,
"tezina": 1,
"lepota": 1,
"uspon": 1,
"spust": 1,
"polazak": ["Popovica","Zmajevac"],
"mark": 1,
"bus": 1,
"bike": 1,
"kruzna": 1,
"opis1":"Jako lepa staza",
"opsirnije":"0",
"t_geojson":{},
"id_u_nizu": 99999
},
{
"id": 3019,
"tip": "setnja",
"grupa": 2,
"ime": "PS_FGM_13_MaliZapadZapad",
"gpxime": "PS_FGM_13_MaliZapadZapad.gpx",
"oznaka": "FGMaraton_32.png",
"stil": "crvena_1",
"duzina": 1,
"tezina": 1,
"lepota": 1,
"uspon": 1,
"spust": 1,
"polazak": ["Popovica","Zmajevac"],
"mark": 1,
"bus": 1,
"bike": 1,
"kruzna": 1,
"opis1":"Jako lepa staza",
"opsirnije":"0",
"t_geojson":{},
"id_u_nizu": 99999
},
{
"id": 3020,
"tip": "setnja",
"grupa": 2,
"ime": "PS_FGM_14_PripravnickiJuzni",
"gpxime": "PS_FGM_14_PripravnickiJuzni.gpx",
"oznaka": "FGMaraton_32.png",
"stil": "crvena_1",
"duzina": 1,
"tezina": 1,
"lepota": 1,
"uspon": 1,
"spust": 1,
"polazak": ["Popovica","Zmajevac"],
"mark": 1,
"bus": 1,
"bike": 1,
"kruzna": 1,
"opis1":"Jako lepa staza",
"opsirnije":"0",
"t_geojson":{},
"id_u_nizu": 99999
},
{
"id": 3021,
"tip": "setnja",
"grupa": 2,
"ime": "PS_FGM_15_PripravnickiZapadZapad",
"gpxime": "PS_FGM_15_PripravnickiZapadZapad.gpx",
"oznaka": "FGMaraton_32.png",
"stil": "crvena_1",
"duzina": 1,
"tezina": 1,
"lepota": 1,
"uspon": 1,
"spust": 1,
"polazak": ["Popovica","Zmajevac"],
"mark": 1,
"bus": 1,
"bike": 1,
"kruzna": 1,
"opis1":"Jako lepa staza",
"opsirnije":"0",
"t_geojson":{},
"id_u_nizu": 99999
},
{
"id": 3022,
"tip": "setnja",
"grupa": 2,
"ime": "PS_FGM_16_PripravnickiZapadni",
"gpxime": "PS_FGM_16_PripravnickiZapadni.gpx",
"oznaka": "FGMaraton_32.png",
"stil": "crvena_1",
"duzina": 1,
"tezina": 1,
"lepota": 1,
"uspon": 1,
"spust": 1,
"polazak": ["Popovica","Zmajevac"],
"mark": 1,
"bus": 1,
"bike": 1,
"kruzna": 1,
"opis1":"Jako lepa staza",
"opsirnije":"0",
"t_geojson":{},
"id_u_nizu": 99999
},
{
"id": 3023,
"tip": "setnja",
"grupa": 2,
"ime": "PS_FGM_17_PripravnickiIstocni",
"gpxime": "PS_FGM_17_PripravnickiIstocni.gpx",
"oznaka": "FGMaraton_32.png",
"stil": "crvena_1",
"duzina": 1,
"tezina": 1,
"lepota": 1,
"uspon": 1,
"spust": 1,
"polazak": ["Popovica","Zmajevac"],
"mark": 1,
"bus": 1,
"bike": 1,
"kruzna": 1,
"opis1":"Jako lepa staza",
"opsirnije":"0",
"t_geojson":{},
"id_u_nizu": 99999
},
{
"id": 3024,
"tip": "setnja",
"grupa": 2,
"ime": "PS_FGM_18_PripravnickiMini",
"gpxime": "PS_FGM_18_PripravnickiMini.gpx",
"oznaka": "FGMaraton_32.png",
"stil": "crvena_1",
"duzina": 1,
"tezina": 1,
"lepota": 1,
"uspon": 1,
"spust": 1,
"polazak": ["Popovica","Zmajevac"],
"mark": 1,
"bus": 1,
"bike": 1,
"kruzna": 1,
"opis1":"Jako lepa staza",
"opsirnije":"0",
"t_geojson":{},
"id_u_nizu": 99999
},
{
"id": 3025,
"tip": "setnja",
"grupa": 2,
"ime": "PS_FGM_19_RadostZadovoljstvo",
"gpxime": "PS_FGM_19_RadostZadovoljstvo.gpx",
"oznaka": "FGMaraton_32.png",
"stil": "crvena_1",
"duzina": 1,
"tezina": 1,
"lepota": 1,
"uspon": 1,
"spust": 1,
"polazak": ["Popovica","Zmajevac"],
"mark": 1,
"bus": 1,
"bike": 1,
"kruzna": 1,
"opis1":"Jako lepa staza",
"opsirnije":"0",
"t_geojson":{},
"id_u_nizu": 99999
},
{
"id": 3026,
"tip": "setnja",
"grupa": 2,
"ime": "PS_FruskaGora_Maraton_SveStaze&WP",
"gpxime": "PS_FruskaGora_Maraton_SveStaze&WP.gpx",
"oznaka": "FGMaraton_32.png",
"stil": "crvena_1",
"duzina": 1,
"tezina": 1,
"lepota": 1,
"uspon": 1,
"spust": 1,
"polazak": ["Popovica","Zmajevac"],
"mark": 1,
"bus": 1,
"bike": 1,
"kruzna": 1,
"opis1":"Jako lepa staza",
"opsirnije":"0",
"t_geojson":{},
"id_u_nizu": 99999
},
{
"id": 3027,
"tip": "setnja",
"grupa": 2,
"ime": "PS_FruskaGora_Maraton_SveStaze",
"gpxime": "PS_FruskaGora_Maraton_SveStaze.gpx",
"oznaka": "FGMaraton_32.png",
"stil": "crvena_1",
"duzina": 1,
"tezina": 1,
"lepota": 1,
"uspon": 1,
"spust": 1,
"polazak": ["Popovica","Zmajevac"],
"mark": 1,
"bus": 1,
"bike": 1,
"kruzna": 1,
"opis1":"Jako lepa staza",
"opsirnije":"0",
"t_geojson":{},
"id_u_nizu": 99999
},
{
"id": 3028,
"tip": "setnja",
"grupa": 2,
"ime": "PS_FruskaGora_Maraton_SviWP",
"gpxime": "PS_FruskaGora_Maraton_SviWP.gpx",
"oznaka": "FGMaraton_32.png",
"stil": "crvena_1",
"duzina": 1,
"tezina": 1,
"lepota": 1,
"uspon": 1,
"spust": 1,
"polazak": ["Popovica","Zmajevac"],
"mark": 1,
"bus": 1,
"bike": 1,
"kruzna": 1,
"opis1":"Jako lepa staza",
"opsirnije":"0",
"t_geojson":{},
"id_u_nizu": 99999
},
{
"id": 3029,
"tip": "setnja",
"grupa": 3,
"ime": "PS_BM_01_Veliki",
"gpxime": "PS_BM_01_Veliki.gpx",
"oznaka": "BMaraton_32.png",
"stil": "crvena_2",
"duzina": 1,
"tezina": 1,
"lepota": 1,
"uspon": 1,
"spust": 1,
"polazak": ["Popovica","Zmajevac"],
"mark": 1,
"bus": 1,
"bike": 1,
"kruzna": 1,
"opis1":"Jako lepa staza",
"opsirnije":"0",
"t_geojson":{},
"id_u_nizu": 99999
},
{
"id": 3030,
"tip": "setnja",
"grupa": 3,
"ime": "PS_BM_02_SrednjiZapadni",
"gpxime": "PS_BM_02_SrednjiZapadni.gpx",
"oznaka": "BMaraton_32.png",
"stil": "crvena_2",
"duzina": 1,
"tezina": 1,
"lepota": 1,
"uspon": 1,
"spust": 1,
"polazak": ["Popovica","Zmajevac"],
"mark": 1,
"bus": 1,
"bike": 1,
"kruzna": 1,
"opis1":"Jako lepa staza",
"opsirnije":"0",
"t_geojson":{},
"id_u_nizu": 99999
},
{
"id": 3031,
"tip": "setnja",
"grupa": 3,
"ime": "PS_BM_03_SrednjiIstocni",
"gpxime": "PS_BM_03_SrednjiIstocni.gpx",
"oznaka": "BMaraton_32.png",
"stil": "crvena_2",
"duzina": 1,
"tezina": 1,
"lepota": 1,
"uspon": 1,
"spust": 1,
"polazak": ["Popovica","Zmajevac"],
"mark": 1,
"bus": 1,
"bike": 1,
"kruzna": 1,
"opis1":"Jako lepa staza",
"opsirnije":"0",
"t_geojson":{},
"id_u_nizu": 99999
},
{
"id": 3032,
"tip": "setnja",
"grupa": 3,
"ime": "PS_BM_04_Mali",
"gpxime": "PS_BM_04_Mali.gpx",
"oznaka": "BMaraton_32.png",
"stil": "crvena_2",
"duzina": 1,
"tezina": 1,
"lepota": 1,
"uspon": 1,
"spust": 1,
"polazak": ["Popovica","Zmajevac"],
"mark": 1,
"bus": 1,
"bike": 1,
"kruzna": 1,
"opis1":"Jako lepa staza",
"opsirnije":"0",
"t_geojson":{},
"id_u_nizu": 99999
},
{
"id": 3033,
"tip": "setnja",
"grupa": 3,
"ime": "PS_BM_05_Osnovni",
"gpxime": "PS_BM_05_Osnovni.gpx",
"oznaka": "BMaraton_32.png",
"stil": "crvena_2",
"duzina": 1,
"tezina": 1,
"lepota": 1,
"uspon": 1,
"spust": 1,
"polazak": ["Popovica","Zmajevac"],
"mark": 1,
"bus": 1,
"bike": 1,
"kruzna": 1,
"opis1":"Jako lepa staza",
"opsirnije":"0",
"t_geojson":{},
"id_u_nizu": 99999
},
{
"id": 3034,
"tip": "setnja",
"grupa": 3,
"ime": "PS_BM_06_ZaNajmladje",
"gpxime": "PS_BM_06_ZaNajmladje.gpx",
"oznaka": "BMaraton_32.png",
"stil": "crvena_2",
"duzina": 1,
"tezina": 1,
"lepota": 1,
"uspon": 1,
"spust": 1,
"polazak": ["Popovica","Zmajevac"],
"mark": 1,
"bus": 1,
"bike": 1,
"kruzna": 1,
"opis1":"Jako lepa staza",
"opsirnije":"0",
"t_geojson":{},
"id_u_nizu": 99999
},
{
"id": 3035,
"tip": "setnja",
"grupa": 3,
"ime": "PS_FruskaGora_BukovackiMaraton_SveStaze&WP",
"gpxime": "PS_FruskaGora_BukovackiMaraton_SveStaze&WP.gpx",
"oznaka": "BMaraton_32.png",
"stil": "crvena_2",
"duzina": 1,
"tezina": 1,
"lepota": 1,
"uspon": 1,
"spust": 1,
"polazak": ["Popovica","Zmajevac"],
"mark": 1,
"bus": 1,
"bike": 1,
"kruzna": 1,
"opis1":"Jako lepa staza",
"opsirnije":"0",
"t_geojson":{},
"id_u_nizu": 99999
},
{
"id": 3036,
"tip": "setnja",
"grupa": 4,
"ime": "PS_FG_P01_Izvorska",
"gpxime": "PS_FG_P01_Izvorska.gpx",
"oznaka": "CrvenoBela_Kruznica_Standardna_32.png",
"stil": "crvena_3",
"duzina": 1,
"tezina": 1,
"lepota": 1,
"uspon": 1,
"spust": 1,
"polazak": ["Popovica","Zmajevac"],
"mark": 1,
"bus": 1,
"bike": 1,
"kruzna": 1,
"opis1":"Jako lepa staza",
"opsirnije":"0",
"t_geojson":{},
"id_u_nizu": 99999
},
{
"id": 3037,
"tip": "setnja",
"grupa": 4,
"ime": "PS_FG_P02a_Vilenjacka1",
"gpxime": "PS_FG_P02a_Vilenjacka1.gpx",
"oznaka": "CrvenoPlava_Kruznica_Vilenjacka_32.png",
"stil": "crvena_3",
"duzina": 1,
"tezina": 1,
"lepota": 1,
"uspon": 1,
"spust": 1,
"polazak": ["Popovica","Zmajevac"],
"mark": 1,
"bus": 1,
"bike": 1,
"kruzna": 1,
"opis1":"Jako lepa staza",
"opsirnije":"0",
"t_geojson":{},
"id_u_nizu": 99999
},
{
"id": 3038,
"tip": "setnja",
"grupa": 4,
"ime": "PS_FG_P02b_Vilenjacka2",
"gpxime": "PS_FG_P02b_Vilenjacka2.gpx",
"oznaka": "CrvenoPlava_Kruznica_Vilenjacka_32.png",
"stil": "crvena_3",
"duzina": 1,
"tezina": 1,
"lepota": 1,
"uspon": 1,
"spust": 1,
"polazak": ["Popovica","Zmajevac"],
"mark": 1,
"bus": 1,
"bike": 1,
"kruzna": 1,
"opis1":"Jako lepa staza",
"opsirnije":"0",
"t_geojson":{},
"id_u_nizu": 99999
},
{
"id": 3039,
"tip": "setnja",
"grupa": 4,
"ime": "PS_FG_P02c_Vilenjacka3",
"gpxime": "PS_FG_P02c_Vilenjacka3.gpx",
"oznaka": "CrvenoPlava_Kruznica_Vilenjacka_32.png",
"stil": "crvena_3",
"duzina": 1,
"tezina": 1,
"lepota": 1,
"uspon": 1,
"spust": 1,
"polazak": ["Popovica","Zmajevac"],
"mark": 1,
"bus": 1,
"bike": 1,
"kruzna": 1,
"opis1":"Jako lepa staza",
"opsirnije":"0",
"t_geojson":{},
"id_u_nizu": 99999
},
{
"id": 3040,
"tip": "setnja",
"grupa": 4,
"ime": "PS_FG_P03_Monaska",
"gpxime": "PS_FG_P03_Monaska.gpx",
"oznaka": "Monaska_32.png",
"stil": "crvena_3",
"duzina": 1,
"tezina": 1,
"lepota": 1,
"uspon": 1,
"spust": 1,
"polazak": ["Popovica","Zmajevac"],
"mark": 1,
"bus": 1,
"bike": 1,
"kruzna": 1,
"opis1":"Jako lepa staza",
"opsirnije":"0",
"t_geojson":{},
"id_u_nizu": 99999
},
{
"id": 3041,
"tip": "setnja",
"grupa": 4,
"ime": "PS_FG_P04_Postarska",
"gpxime": "PS_FG_P04_Postarska.gpx",
"oznaka": "CrvenoBela_Kruznica_Standardna_32.png",
"stil": "crvena_3",
"duzina": 1,
"tezina": 1,
"lepota": 1,
"uspon": 1,
"spust": 1,
"polazak": ["Popovica","Zmajevac"],
"mark": 1,
"bus": 1,
"bike": 1,
"kruzna": 1,
"opis1":"Jako lepa staza",
"opsirnije":"0",
"t_geojson":{},
"id_u_nizu": 99999
},
{
"id": 3042,
"tip": "setnja",
"grupa": 4,
"ime": "PS_FG_P05_Lazina",
"gpxime": "PS_FG_P05_Lazina.gpx",
"oznaka": "LazinaSaka_32.png",
"stil": "crvena_3",
"duzina": 1,
"tezina": 1,
"lepota": 1,
"uspon": 1,
"spust": 1,
"polazak": ["Popovica","Zmajevac"],
"mark": 1,
"bus": 1,
"bike": 1,
"kruzna": 1,
"opis1":"Jako lepa staza",
"opsirnije":"0",
"t_geojson":{},
"id_u_nizu": 99999
},
{
"id": 3043,
"tip": "setnja",
"grupa": 4,
"ime": "PS_FG_P06_Brankovac-CrveniCot",
"gpxime": "PS_FG_P06_Brankovac-CrveniCot.gpx",
"oznaka": "CrvenoBela_Kruznica_Standardna_32.png",
"stil": "crvena_3",
"duzina": 1,
"tezina": 1,
"lepota": 1,
"uspon": 1,
"spust": 1,
"polazak": ["Popovica","Zmajevac"],
"mark": 1,
"bus": 1,
"bike": 1,
"kruzna": 1,
"opis1":"Jako lepa staza",
"opsirnije":"0",
"t_geojson":{},
"id_u_nizu": 99999
},
{
"id": 3044,
"tip": "setnja",
"grupa": 4,
"ime": "PS_FG_P07_Partizanska",
"gpxime": "PS_FG_P07_Partizanska.gpx",
"oznaka": "Petokraka_Partizanska_32.png",
"stil": "crvena_3",
"duzina": 1,
"tezina": 1,
"lepota": 1,
"uspon": 1,
"spust": 1,
"polazak": ["Popovica","Zmajevac"],
"mark": 1,
"bus": 1,
"bike": 1,
"kruzna": 1,
"opis1":"Jako lepa staza",
"opsirnije":"0",
"t_geojson":{},
"id_u_nizu": 99999
},
{
"id": 3045,
"tip": "setnja",
"grupa": 4,
"ime": "PS_FG_P08_GradacSenderoLuminoso",
"gpxime": "PS_FG_P08_GradacSenderoLuminoso.gpx",
"oznaka": "FluoZelenoNarandzasta_32.png",
"stil": "crvena_3",
"duzina": 1,
"tezina": 1,
"lepota": 1,
"uspon": 1,
"spust": 1,
"polazak": ["Popovica","Zmajevac"],
"mark": 1,
"bus": 1,
"bike": 1,
"kruzna": 1,
"opis1":"Jako lepa staza",
"opsirnije":"0",
"t_geojson":{},
"id_u_nizu": 99999
},
{
"id": 3046,
"tip": "setnja",
"grupa": 4,
"ime": "PS_FG_SZ01_PopovicaPlava",
"gpxime": "PS_FG_SZ01_PopovicaPlava.gpx",
"oznaka": "PlavaTacka_32.png",
"stil": "crvena_3",
"duzina": 1,
"tezina": 1,
"lepota": 1,
"uspon": 1,
"spust": 1,
"polazak": ["Popovica","Zmajevac"],
"mark": 1,
"bus": 1,
"bike": 1,
"kruzna": 1,
"opis1":"Jako lepa staza",
"opsirnije":"0",
"t_geojson":{},
"id_u_nizu": 99999
},
{
"id": 3047,
"tip": "setnja",
"grupa": 4,
"ime": "PS_FG_SZ02_PopovicaZelena",
"gpxime": "PS_FG_SZ02_PopovicaZelena.gpx",
"oznaka": "ZelenaTacka_32.png",
"stil": "crvena_3",
"duzina": 1,
"tezina": 1,
"lepota": 1,
"uspon": 1,
"spust": 1,
"polazak": ["Popovica","Zmajevac"],
"mark": 1,
"bus": 1,
"bike": 1,
"kruzna": 1,
"opis1":"Jako lepa staza",
"opsirnije":"0",
"t_geojson":{},
"id_u_nizu": 99999
},
{
"id": 3048,
"tip": "setnja",
"grupa": 4,
"ime": "PS_FG_SZ03_StrazilovoZelena",
"gpxime": "PS_FG_SZ03_StrazilovoZelena.gpx",
"oznaka": "ZelenaTacka_32.png",
"stil": "crvena_3",
"duzina": 1,
"tezina": 1,
"lepota": 1,
"uspon": 1,
"spust": 1,
"polazak": ["Popovica","Zmajevac"],
"mark": 1,
"bus": 1,
"bike": 1,
"kruzna": 1,
"opis1":"Jako lepa staza",
"opsirnije":"0",
"t_geojson":{},
"id_u_nizu": 99999
},
{
"id": 3049,
"tip": "setnja",
"grupa": 4,
"ime": "PS_FG_SZ05_Osovlje2_Duza",
"gpxime": "PS_FG_SZ05_Osovlje2_Duza.gpx",
"oznaka": "CrvenoBela_Kruznica_Standardna_32.png",
"stil": "crvena_3",
"duzina": 1,
"tezina": 1,
"lepota": 1,
"uspon": 1,
"spust": 1,
"polazak": ["Popovica","Zmajevac"],
"mark": 1,
"bus": 1,
"bike": 1,
"kruzna": 1,
"opis1":"Jako lepa staza",
"opsirnije":"0",
"t_geojson":{},
"id_u_nizu": 99999
},
{
"id": 3050,
"tip": "setnja",
"grupa": 4,
"ime": "PS_FG_SZ06_Osovlje1_Kraca",
"gpxime": "PS_FG_SZ06_Osovlje1_Kraca.gpx",
"oznaka": "CrvenoBela_Kruznica_Standardna_32.png",
"stil": "crvena_3",
"duzina": 1,
"tezina": 1,
"lepota": 1,
"uspon": 1,
"spust": 1,
"polazak": ["Popovica","Zmajevac"],
"mark": 1,
"bus": 1,
"bike": 1,
"kruzna": 1,
"opis1":"Jako lepa staza",
"opsirnije":"0",
"t_geojson":{},
"id_u_nizu": 99999
},
{
"id": 3051,
"tip": "setnja",
"grupa": 4,
"ime": "PS_FG_SZ07_Morintovo",
"gpxime": "PS_FG_SZ07_Morintovo.gpx",
"oznaka": "CrvenoBela_Kruznica_Standardna_32.png",
"stil": "crvena_3",
"duzina": 1,
"tezina": 1,
"lepota": 1,
"uspon": 1,
"spust": 1,
"polazak": ["Popovica","Zmajevac"],
"mark": 1,
"bus": 1,
"bike": 1,
"kruzna": 1,
"opis1":"Jako lepa staza",
"opsirnije":"0",
"t_geojson":{},
"id_u_nizu": 99999
},
{
"id": 3052,
"tip": "setnja",
"grupa": 5,
"ime": "PS_FG_M07(braon)_ZimskaSluzba-Norcev",
"gpxime": "PS_FG_M07(braon)_ZimskaSluzba-Norcev.gpx",
"oznaka": "Braon_32.png",
"stil": "braon_0",
"duzina": 1,
"tezina": 1,
"lepota": 1,
"uspon": 1,
"spust": 1,
"polazak": ["Popovica","Zmajevac"],
"mark": 1,
"bus": 1,
"bike": 1,
"kruzna": 1,
"opis1":"Jako lepa staza",
"opsirnije":"0",
"t_geojson":{},
"id_u_nizu": 99999
},
{
"id": 3053,
"tip": "setnja",
"grupa": 5,
"ime": "PS_FG_M10(braon)_PDVojvodina-NovoHopovo-StaroHopovo-PartizanskiPut",
"gpxime": "PS_FG_M10(braon)_PDVojvodina-NovoHopovo-StaroHopovo-PartizanskiPut.gpx",
"oznaka": "Braon_32.png",
"stil": "braon_0",
"duzina": 1,
"tezina": 1,
"lepota": 1,
"uspon": 1,
"spust": 1,
"polazak": ["Popovica","Zmajevac"],
"mark": 1,
"bus": 1,
"bike": 1,
"kruzna": 1,
"opis1":"Jako lepa staza",
"opsirnije":"0",
"t_geojson":{},
"id_u_nizu": 99999
},
{
"id": 3054,
"tip": "setnja",
"grupa": 5,
"ime": "PS_FG_M22(braon)_Cerevic-KatanskeLivade-Isajlovac",
"gpxime": "PS_FG_M22(braon)_Cerevic-KatanskeLivade-Isajlovac.gpx",
"oznaka": "Braon_32.png",
"stil": "braon_0",
"duzina": 1,
"tezina": 1,
"lepota": 1,
"uspon": 1,
"spust": 1,
"polazak": ["Popovica","Zmajevac"],
"mark": 1,
"bus": 1,
"bike": 1,
"kruzna": 1,
"opis1":"Jako lepa staza",
"opsirnije":"0",
"t_geojson":{},
"id_u_nizu": 99999
},
{
"id": 3055,
"tip": "setnja",
"grupa": 6,
"ime": "PS_FG_M04(crna)_Glavica-VilinaVodica-Strazilovo",
"gpxime": "PS_FG_M04(crna)_Glavica-VilinaVodica-Strazilovo.gpx",
"oznaka": "Crna_32.png",
"stil": "crna_0",
"duzina": 1,
"tezina": 1,
"lepota": 1,
"uspon": 1,
"spust": 1,
"polazak": ["Popovica","Zmajevac"],
"mark": 1,
"bus": 1,
"bike": 1,
"kruzna": 1,
"opis1":"Jako lepa staza",
"opsirnije":"0",
"t_geojson":{},
"id_u_nizu": 99999
},
{
"id": 3056,
"tip": "setnja",
"grupa": 6,
"ime": "PS_FG_M08(crna)_ZimskaSluzba-TVtoranj",
"gpxime": "PS_FG_M08(crna)_ZimskaSluzba-TVtoranj.gpx",
"oznaka": "Crna_32.png",
"stil": "crna_0",
"duzina": 1,
"tezina": 1,
"lepota": 1,
"uspon": 1,
"spust": 1,
"polazak": ["Popovica","Zmajevac"],
"mark": 1,
"bus": 1,
"bike": 1,
"kruzna": 1,
"opis1":"Jako lepa staza",
"opsirnije":"0",
"t_geojson":{},
"id_u_nizu": 99999
},
{
"id": 3057,
"tip": "setnja",
"grupa": 6,
"ime": "PS_FG_M21(crna)_Cerevic-KozjeBrdo-Osovlje",
"gpxime": "PS_FG_M21(crna)_Cerevic-KozjeBrdo-Osovlje.gpx",
"oznaka": "Crna_32.png",
"stil": "crna_0",
"duzina": 1,
"tezina": 1,
"lepota": 1,
"uspon": 1,
"spust": 1,
"polazak": ["Popovica","Zmajevac"],
"mark": 1,
"bus": 1,
"bike": 1,
"kruzna": 1,
"opis1":"Jako lepa staza",
"opsirnije":"0",
"t_geojson":{},
"id_u_nizu": 99999
},
{
"id": 3058,
"tip": "setnja",
"grupa": 6,
"ime": "PS_FG_M32(crna)_Stranputica-Gredelj",
"gpxime": "PS_FG_M32(crna)_Stranputica-Gredelj.gpx",
"oznaka": "Crna_32.png",
"stil": "crna_0",
"duzina": 1,
"tezina": 1,
"lepota": 1,
"uspon": 1,
"spust": 1,
"polazak": ["Popovica","Zmajevac"],
"mark": 1,
"bus": 1,
"bike": 1,
"kruzna": 1,
"opis1":"Jako lepa staza",
"opsirnije":"0",
"t_geojson":{},
"id_u_nizu": 99999
},
{
"id": 3059,
"tip": "setnja",
"grupa": 7,
"ime": "PS_FG_M02(crvena)_Strazilovo-ManastirGrgrteg",
"gpxime": "PS_FG_M02(crvena)_Strazilovo-ManastirGrgrteg.gpx",
"oznaka": "Crvena_32.png",
"stil": "crvena_4",
"duzina": 1,
"tezina": 1,
"lepota": 1,
"uspon": 1,
"spust": 1,
"polazak": ["Popovica","Zmajevac"],
"mark": 1,
"bus": 1,
"bike": 1,
"kruzna": 1,
"opis1":"Jako lepa staza",
"opsirnije":"0",
"t_geojson":{},
"id_u_nizu": 99999
},
{
"id": 3060,
"tip": "setnja",
"grupa": 7,
"ime": "PS_FG_M05(crvena)_ZimskaSluzba-VilinaVodica-Bukovac",
"gpxime": "PS_FG_M05(crvena)_ZimskaSluzba-VilinaVodica-Bukovac.gpx",
"oznaka": "Crvena_32.png",
"stil": "crvena_4",
"duzina": 1,
"tezina": 1,
"lepota": 1,
"uspon": 1,
"spust": 1,
"polazak": ["Popovica","Zmajevac"],
"mark": 1,
"bus": 1,
"bike": 1,
"kruzna": 1,
"opis1":"Jako lepa staza",
"opsirnije":"0",
"t_geojson":{},
"id_u_nizu": 99999
},
{
"id": 3061,
"tip": "setnja",
"grupa": 7,
"ime": "PS_FG_M16(crvena)_InstitutVenac-Morintovo-ManastirRavanica",
"gpxime": "PS_FG_M16(crvena)_InstitutVenac-Morintovo-ManastirRavanica.gpx",
"oznaka": "Crvena_32.png",
"stil": "crvena_4",
"duzina": 1,
"tezina": 1,
"lepota": 1,
"uspon": 1,
"spust": 1,
"polazak": ["Popovica","Zmajevac"],
"mark": 1,
"bus": 1,
"bike": 1,
"kruzna": 1,
"opis1":"Jako lepa staza",
"opsirnije":"0",
"t_geojson":{},
"id_u_nizu": 99999
},
{
"id": 3062,
"tip": "setnja",
"grupa": 7,
"ime": "PS_FG_M18(crvena)_St.Ledinci-Kamenolom-Zmajevac",
"gpxime": "PS_FG_M18(crvena)_St.Ledinci-Kamenolom-Zmajevac.gpx",
"oznaka": "Crvena_32.png",
"stil": "crvena_4",
"duzina": 1,
"tezina": 1,
"lepota": 1,
"uspon": 1,
"spust": 1,
"polazak": ["Popovica","Zmajevac"],
"mark": 1,
"bus": 1,
"bike": 1,
"kruzna": 1,
"opis1":"Jako lepa staza",
"opsirnije":"0",
"t_geojson":{},
"id_u_nizu": 99999
},
{
"id": 3063,
"tip": "setnja",
"grupa": 7,
"ime": "PS_FG_M25(crvena)_ManastirBeocin-Osovlje-PavlasovCot",
"gpxime": "PS_FG_M25(crvena)_ManastirBeocin-Osovlje-PavlasovCot.gpx",
"oznaka": "Crvena_32.png",
"stil": "crvena_4",
"duzina": 1,
"tezina": 1,
"lepota": 1,
"uspon": 1,
"spust": 1,
"polazak": ["Popovica","Zmajevac"],
"mark": 1,
"bus": 1,
"bike": 1,
"kruzna": 1,
"opis1":"Jako lepa staza",
"opsirnije":"0",
"t_geojson":{},
"id_u_nizu": 99999
},
{
"id": 3064,
"tip": "setnja",
"grupa": 7,
"ime": "PS_FG_M26(crvena)_ManastirBeocin-Brankovac",
"gpxime": "PS_FG_M26(crvena)_ManastirBeocin-Brankovac.gpx",
"oznaka": "Crvena_32.png",
"stil": "crvena_4",
"duzina": 1,
"tezina": 1,
"lepota": 1,
"uspon": 1,
"spust": 1,
"polazak": ["Popovica","Zmajevac"],
"mark": 1,
"bus": 1,
"bike": 1,
"kruzna": 1,
"opis1":"Jako lepa staza",
"opsirnije":"0",
"t_geojson":{},
"id_u_nizu": 99999
},
{
"id": 3065,
"tip": "setnja",
"grupa": 7,
"ime": "PS_FG_M33(crvena2)_KraljevaStolicaKT-LazinVir",
"gpxime": "PS_FG_M33(crvena2)_KraljevaStolicaKT-LazinVir.gpx",
"oznaka": "Crvena_32.png",
"stil": "crvena_4",
"duzina": 1,
"tezina": 1,
"lepota": 1,
"uspon": 1,
"spust": 1,
"polazak": ["Popovica","Zmajevac"],
"mark": 1,
"bus": 1,
"bike": 1,
"kruzna": 1,
"opis1":"Jako lepa staza",
"opsirnije":"0",
"t_geojson":{},
"id_u_nizu": 99999
},
{
"id": 3066,
"tip": "setnja",
"grupa": 7,
"ime": "PS_FG_M34(crvena)_IzvorKucurinaVrdnik-PDomZmajevac",
"gpxime": "PS_FG_M34(crvena)_IzvorKucurinaVrdnik-PDomZmajevac.gpx",
"oznaka": "Crvena_32.png",
"stil": "crvena_4",
"duzina": 1,
"tezina": 1,
"lepota": 1,
"uspon": 1,
"spust": 1,
"polazak": ["Popovica","Zmajevac"],
"mark": 1,
"bus": 1,
"bike": 1,
"kruzna": 1,
"opis1":"Jako lepa staza",
"opsirnije":"0",
"t_geojson":{},
"id_u_nizu": 99999
},
{
"id": 3067,
"tip": "setnja",
"grupa": 8,
"ime": "PS_FG_M01(plava)_Strazilovo-VelikaRemeta-Grgeteg-TVtoranj",
"gpxime": "PS_FG_M01(plava)_Strazilovo-VelikaRemeta-Grgeteg-TVtoranj.gpx",
"oznaka": "Plava_32.png",
"stil": "plava_0",
"duzina": 1,
"tezina": 1,
"lepota": 1,
"uspon": 1,
"spust": 1,
"polazak": ["Popovica","Zmajevac"],
"mark": 1,
"bus": 1,
"bike": 1,
"kruzna": 1,
"opis1":"Jako lepa staza",
"opsirnije":"0",
"t_geojson":{},
"id_u_nizu": 99999
},
{
"id": 3068,
"tip": "setnja",
"grupa": 8,
"ime": "PS_FG_M09(plava)_Hangar-VenacSpomenikNOB",
"gpxime": "PS_FG_M09(plava)_Hangar-VenacSpomenikNOB.gpx",
"oznaka": "Plava_32.png",
"stil": "plava_0",
"duzina": 1,
"tezina": 1,
"lepota": 1,
"uspon": 1,
"spust": 1,
"polazak": ["Popovica","Zmajevac"],
"mark": 1,
"bus": 1,
"bike": 1,
"kruzna": 1,
"opis1":"Jako lepa staza",
"opsirnije":"0",
"t_geojson":{},
"id_u_nizu": 99999
},
{
"id": 3069,
"tip": "setnja",
"grupa": 8,
"ime": "PS_FG_M20(plava)_ManastirJazak-Brankovac",
"gpxime": "PS_FG_M20(plava)_ManastirJazak-Brankovac.gpx",
"oznaka": "Plava_32.png",
"stil": "plava_0",
"duzina": 1,
"tezina": 1,
"lepota": 1,
"uspon": 1,
"spust": 1,
"polazak": ["Popovica","Zmajevac"],
"mark": 1,
"bus": 1,
"bike": 1,
"kruzna": 1,
"opis1":"Jako lepa staza",
"opsirnije":"0",
"t_geojson":{},
"id_u_nizu": 99999
},
{
"id": 3070,
"tip": "setnja",
"grupa": 8,
"ime": "PS_FG_M24(plava)_StariRakovac-Vadjevine",
"gpxime": "PS_FG_M24(plava)_StariRakovac-Vadjevine.gpx",
"oznaka": "Plava_32.png",
"stil": "plava_0",
"duzina": 1,
"tezina": 1,
"lepota": 1,
"uspon": 1,
"spust": 1,
"polazak": ["Popovica","Zmajevac"],
"mark": 1,
"bus": 1,
"bike": 1,
"kruzna": 1,
"opis1":"Jako lepa staza",
"opsirnije":"0",
"t_geojson":{},
"id_u_nizu": 99999
},
{
"id": 3071,
"tip": "setnja",
"grupa": 8,
"ime": "PS_FG_M29(plava)_Letenka-Grabovacki(Crni)Vodopad",
"gpxime": "PS_FG_M29(plava)_Letenka-Grabovacki(Crni)Vodopad.gpx",
"oznaka": "Plava_32.png",
"stil": "plava_0",
"duzina": 1,
"tezina": 1,
"lepota": 1,
"uspon": 1,
"spust": 1,
"polazak": ["Popovica","Zmajevac"],
"mark": 1,
"bus": 1,
"bike": 1,
"kruzna": 1,
"opis1":"Jako lepa staza",
"opsirnije":"0",
"t_geojson":{},
"id_u_nizu": 99999
},
{
"id": 3072,
"tip": "setnja",
"grupa": 8,
"ime": "PS_FG_M30(plava)_Popradine-MasnaCupa",
"gpxime": "PS_FG_M30(plava)_Popradine-MasnaCupa.gpx",
"oznaka": "Plava_32.png",
"stil": "plava_0",
"duzina": 1,
"tezina": 1,
"lepota": 1,
"uspon": 1,
"spust": 1,
"polazak": ["Popovica","Zmajevac"],
"mark": 1,
"bus": 1,
"bike": 1,
"kruzna": 1,
"opis1":"Jako lepa staza",
"opsirnije":"0",
"t_geojson":{},
"id_u_nizu": 99999
},
{
"id": 3073,
"tip": "setnja",
"grupa": 8,
"ime": "PS_FG_M31(plava)_Stranputica-CrveniCot",
"gpxime": "PS_FG_M31(plava)_Stranputica-CrveniCot.gpx",
"oznaka": "Plava_32.png",
"stil": "plava_0",
"duzina": 1,
"tezina": 1,
"lepota": 1,
"uspon": 1,
"spust": 1,
"polazak": ["Popovica","Zmajevac"],
"mark": 1,
"bus": 1,
"bike": 1,
"kruzna": 1,
"opis1":"Jako lepa staza",
"opsirnije":"0",
"t_geojson":{},
"id_u_nizu": 99999
},
{
"id": 3074,
"tip": "setnja",
"grupa": 9,
"ime": "PS_FG_M06(zelena)_Paragovo-Glavica-Astal-TVtoranj",
"gpxime": "PS_FG_M06(zelena)_Paragovo-Glavica-Astal-TVtoranj.gpx",
"oznaka": "Zelena_32.png",
"stil": "zelena_0",
"duzina": 1,
"tezina": 1,
"lepota": 1,
"uspon": 1,
"spust": 1,
"polazak": ["Popovica","Zmajevac"],
"mark": 1,
"bus": 1,
"bike": 1,
"kruzna": 1,
"opis1":"Jako lepa staza",
"opsirnije":"0",
"t_geojson":{},
"id_u_nizu": 99999
},
{
"id": 3075,
"tip": "setnja",
"grupa": 9,
"ime": "PS_FG_M11(zelena)_Hangar-VenacSpomenikNOB",
"gpxime": "PS_FG_M11(zelena)_Hangar-VenacSpomenikNOB.gpx",
"oznaka": "Zelena_32.png",
"stil": "zelena_0",
"duzina": 1,
"tezina": 1,
"lepota": 1,
"uspon": 1,
"spust": 1,
"polazak": ["Popovica","Zmajevac"],
"mark": 1,
"bus": 1,
"bike": 1,
"kruzna": 1,
"opis1":"Jako lepa staza",
"opsirnije":"0",
"t_geojson":{},
"id_u_nizu": 99999
},
{
"id": 3076,
"tip": "setnja",
"grupa": 9,
"ime": "PS_FG_M12(zelena)_Vrdnik-Kula",
"gpxime": "PS_FG_M12(zelena)_Vrdnik-Kula.gpx",
"oznaka": "Zelena_32.png",
"stil": "zelena_0",
"duzina": 1,
"tezina": 1,
"lepota": 1,
"uspon": 1,
"spust": 1,
"polazak": ["Popovica","Zmajevac"],
"mark": 1,
"bus": 1,
"bike": 1,
"kruzna": 1,
"opis1":"Jako lepa staza",
"opsirnije":"0",
"t_geojson":{},
"id_u_nizu": 99999
},
{
"id": 3077,
"tip": "setnja",
"grupa": 9,
"ime": "PS_FG_M14(zelena)_IzvorZvecan-PartizanskiPut",
"gpxime": "PS_FG_M14(zelena)_IzvorZvecan-PartizanskiPut.gpx",
"oznaka": "Zelena_32.png",
"stil": "zelena_0",
"duzina": 1,
"tezina": 1,
"lepota": 1,
"uspon": 1,
"spust": 1,
"polazak": ["Popovica","Zmajevac"],
"mark": 1,
"bus": 1,
"bike": 1,
"kruzna": 1,
"opis1":"Jako lepa staza",
"opsirnije":"0",
"t_geojson":{},
"id_u_nizu": 99999
},
{
"id": 3078,
"tip": "setnja",
"grupa": 10,
"ime": "PS_FG_M03(zuta)_ManastirGrgeteg-Neradin-TVtoranj",
"gpxime": "PS_FG_M03(zuta)_ManastirGrgeteg-Neradin-TVtoranj.gpx",
"oznaka": "Zuta_32.png",
"stil": "zuta_0",
"duzina": 1,
"tezina": 1,
"lepota": 1,
"uspon": 1,
"spust": 1,
"polazak": ["Popovica","Zmajevac"],
"mark": 1,
"bus": 1,
"bike": 1,
"kruzna": 1,
"opis1":"Jako lepa staza",
"opsirnije":"0",
"t_geojson":{},
"id_u_nizu": 99999
},
{
"id": 3079,
"tip": "setnja",
"grupa": 10,
"ime": "PS_FG_M13(zuta)_PutZaVenac-Vaga-Zvecan-Jezero",
"gpxime": "PS_FG_M13(zuta)_PutZaVenac-Vaga-Zvecan-Jezero.gpx",
"oznaka": "Zuta_32.png",
"stil": "zuta_0",
"duzina": 1,
"tezina": 1,
"lepota": 1,
"uspon": 1,
"spust": 1,
"polazak": ["Popovica","Zmajevac"],
"mark": 1,
"bus": 1,
"bike": 1,
"kruzna": 1,
"opis1":"Jako lepa staza",
"opsirnije":"0",
"t_geojson":{},
"id_u_nizu": 99999
},
{
"id": 3080,
"tip": "setnja",
"grupa": 10,
"ime": "PS_FG_M17(zuta)_VrdnikTermal-PartizanskiPut",
"gpxime": "PS_FG_M17(zuta)_VrdnikTermal-PartizanskiPut.gpx",
"oznaka": "Zuta_32.png",
"stil": "zuta_0",
"duzina": 1,
"tezina": 1,
"lepota": 1,
"uspon": 1,
"spust": 1,
"polazak": ["Popovica","Zmajevac"],
"mark": 1,
"bus": 1,
"bike": 1,
"kruzna": 1,
"opis1":"Jako lepa staza",
"opsirnije":"0",
"t_geojson":{},
"id_u_nizu": 99999
},
{
"id": 3081,
"tip": "setnja",
"grupa": 10,
"ime": "PS_FG_M19(zuta)_Rakovac-Kesten-Plana-Zmajevac",
"gpxime": "PS_FG_M19(zuta)_Rakovac-Kesten-Plana-Zmajevac.gpx",
"oznaka": "Zuta_32.png",
"stil": "zuta_0",
"duzina": 1,
"tezina": 1,
"lepota": 1,
"uspon": 1,
"spust": 1,
"polazak": ["Popovica","Zmajevac"],
"mark": 1,
"bus": 1,
"bike": 1,
"kruzna": 1,
"opis1":"Jako lepa staza",
"opsirnije":"0",
"t_geojson":{},
"id_u_nizu": 99999
},
{
"id": 3082,
"tip": "setnja",
"grupa": 10,
"ime": "PS_FG_M23(zuta)_Testera-CrveniCot-PavlasovCot",
"gpxime": "PS_FG_M23(zuta)_Testera-CrveniCot-PavlasovCot.gpx",
"oznaka": "Zuta_32.png",
"stil": "zuta_0",
"duzina": 1,
"tezina": 1,
"lepota": 1,
"uspon": 1,
"spust": 1,
"polazak": ["Popovica","Zmajevac"],
"mark": 1,
"bus": 1,
"bike": 1,
"kruzna": 1,
"opis1":"Jako lepa staza",
"opsirnije":"0",
"t_geojson":{},
"id_u_nizu": 99999
},
{
"id": 3083,
"tip": "setnja",
"grupa": 10,
"ime": "PS_FG_M27(zuta)_ManastirBeocin-IsinCot",
"gpxime": "PS_FG_M27(zuta)_ManastirBeocin-IsinCot.gpx",
"oznaka": "Zuta_32.png",
"stil": "zuta_0",
"duzina": 1,
"tezina": 1,
"lepota": 1,
"uspon": 1,
"spust": 1,
"polazak": ["Popovica","Zmajevac"],
"mark": 1,
"bus": 1,
"bike": 1,
"kruzna": 1,
"opis1":"Jako lepa staza",
"opsirnije":"0",
"t_geojson":{},
"id_u_nizu": 99999
},
{
"id": 3084,
"tip": "setnja",
"grupa": 10,
"ime": "PS_FG_M28(zuta)_ManastirBeocin-Osovlje-DobriVodopad-OrlovskeStene",
"gpxime": "PS_FG_M28(zuta)_ManastirBeocin-Osovlje-DobriVodopad-OrlovskeStene.gpx",
"oznaka": "Zuta_32.png",
"stil": "zuta_0",
"duzina": 1,
"tezina": 1,
"lepota": 1,
"uspon": 1,
"spust": 1,
"polazak": ["Popovica","Zmajevac"],
"mark": 1,
"bus": 1,
"bike": 1,
"kruzna": 1,
"opis1":"Jako lepa staza",
"opsirnije":"0",
"t_geojson":{},
"id_u_nizu": 99999
},
{
"id": 3085,
"tip": "setnja",
"grupa": 10,
"ime": "PS_FG_M36(zuta)_IsinCot-NadineKaskade",
"gpxime": "PS_FG_M36(zuta)_IsinCot-NadineKaskade.gpx",
"oznaka": "Zuta_32.png",
"stil": "zuta_0",
"duzina": 1,
"tezina": 1,
"lepota": 1,
"uspon": 1,
"spust": 1,
"polazak": ["Popovica","Zmajevac"],
"mark": 1,
"bus": 1,
"bike": 1,
"kruzna": 1,
"opis1":"Jako lepa staza",
"opsirnije":"0",
"t_geojson":{},
"id_u_nizu": 99999
},


 
        
			]
}	